### ISSUE TITLE
failure in findInheritanceChain when trying to call feature of instance on type feature

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1055]
`fract` is a feature that needs an instance. This should result in a proper error message:
```
ex =>

  c(T type : float T) is
    say T.type.fract

  c f32
```
```
error 1: java.lang.Error: ensure-condition failed: dev.flang.ast.AbstractFeature:findInheritanceChain:1264
	at dev.flang.util.ANY.ensure(ANY.java:236)
	at dev.flang.ast.AbstractFeature.findInheritanceChain(AbstractFeature.java:1264)
	at dev.flang.air.Clazz.findRedefinition(Clazz.java:953)
	at dev.flang.air.Clazz.lookup(Clazz.java:1120)
	at dev.flang.air.Clazzes.findClazzes(Clazzes.java:888)
	at dev.flang.air.Clazz$1.action(Clazz.java:1397)
	at dev.flang.ast.Stmnt.visitStatements(Stmnt.java:72)
	at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:123)
	at dev.flang.ast.Box.visitStatements(Box.java:157)
	at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:117)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractFeature.visitStatements(AbstractFeature.java:1356)
	at dev.flang.air.Clazz.inspectCode(Clazz.java:1347)
	at dev.flang.air.Clazz.findAllClasses(Clazz.java:1391)
	at dev.flang.air.Clazzes.findAllClasses(Clazzes.java:456)
	at dev.flang.fuir.FUIR.<init>(FUIR.java:196)
	at dev.flang.opt.Optimizer.fuir(Optimizer.java:73)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:367)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:832)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:704)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)
```

another flavor:
`c` is never instantiated so `self_referential_feature` is also never instantiated
but via `c.type.a_type_feature` I can call `some_feat_requiring_instance` which is supposed to return an instance
of `self_referential_feature`
```
  self_referential_feature(T type:self_referential_feature T) is
    some_feat_requiring_instance self_referential_feature.this.type is
      self_referential_feature.this
    type.a_type_feature =>
      self_referential_feature.this.type.some_feat_requiring_instance

  c : self_referential_feature c is

  say c.type.a_type_feature
```

**Comment by michaellilltokiwa** [comment]
I just realized that this also happens for type features (e.g. `one`):
```
example =>
  generic_tests(T type: float T) is
    one := T.type.one

  generic_tests f64
```

I was also pondering why `fixed type.one` in `f64` compiles at all. I assume it is because `f64` is predefined in the compiler.
The following example does not compile:
```
example =>

  f64a(val f64a) : float f64a is
    fixed type.one f64a is 1
```
yields:
```
/home/sam/playground/test.fz:4:20: error 1: Type not found
    fixed type.one f64a is 1
-------------------^
Type 'f64a' was not found, no corresponding feature nor formal type parameter exists
Type that was not found: 'f64a'
in feature: 'example.f64a.type.one'
To solve this, check the spelling of the type you have used.
```

**Comment by michaellilltokiwa** [comment]
see also #1377
