### ISSUE TITLE
Feature result type inference from type parameter does not work well

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#1070]
This example shows a surprising result for `type_of_3`:
```
 > cat test_type_result.fz
type_of1(T type, a T) ref Type is T
type_of2(T type, a T) Type is T
type_of3(T type, a T) => T

say (type_of1 3.14)
say (type_of2 3.14)
say (type_of3 3.14)
say (type_of1 "foo")
say (type_of2 "foo")
say (type_of3 "foo")
 > ./build/bin/fz test_type_result.fz
Type of 'f64'
Type of 'f64'
Type of 'Any.type.THIS#TYPE'
Type of 'String'
Type of 'String'
Type of 'Any.type.THIS#TYPE'
```
And it causes a crash using the C backend:
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c test_type_result.fz

error 1: java.lang.Error: require-condition1 failed: dev.flang.air.Clazzes:clazz:1176
	at dev.flang.util.ANY.require(ANY.java:93)
	at dev.flang.air.Clazzes.clazz(Clazzes.java:1176)
	at dev.flang.air.Clazz.actualClazz(Clazz.java:655)
	at dev.flang.air.Clazz.determineResultClazz(Clazz.java:2177)
	at dev.flang.air.Clazz.dependencies(Clazz.java:415)
	at dev.flang.air.Clazzes.create(Clazzes.java:389)
```

**Comment by michaellilltokiwa** [comment]
meanwhile, seems fixed:
```
/home/not_synced/fuzion (issue/1435_remove_unbox)$ cat ~/playground/test.fz 
type_of1(T type, a T) Type is T
type_of2(T type, a T) Type is T
type_of3(T type, a T) => T

say (type_of1 3.14)
say (type_of2 3.14)
say (type_of3 3.14)
say (type_of1 "foo")
say (type_of2 "foo")
say (type_of3 "foo")
/home/not_synced/fuzion (issue/1435_remove_unbox)$ fz -c ~/playground/test.fz 
/home/not_synced/fuzion (issue/1435_remove_unbox)$ ./universe 
Type of 'f64'
Type of 'f64'
Type of 'f64'
Type of 'String'
Type of 'String'
Type of 'String'
/home/not_synced/fuzion (issue/1435_remove_unbox)$ fz  ~/playground/test.fz 
Type of 'f64'
Type of 'f64'
Type of 'f64'
Type of 'String'
Type of 'String'
Type of 'String'
```
