### ISSUE TITLE
Usage numeric.this and type features seem to have side-effects that should not exist

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#1098]
Introduce this change to faebe8e3b434c2c3c42ea56804dbafb9090c7518:
```diff
diff --git a/lib/numeric.fz b/lib/numeric.fz
index 138dc510..75bbff36 100644
--- a/lib/numeric.fz
+++ b/lib/numeric.fz
@@ -31,7 +31,7 @@ numeric(redef T type : numeric T) : has_hash, has_total_order, numerics T is
   # of some features (e.g. prefix -, abs
   thiz T is abstract
 
-  isZero => thiz ≟ zero
+  isZero => numeric.this ≟ numeric.this.type.zero
   isOne  => thiz ≟ one
 
   # basic operations: 'prefix +' (identity)
```
Now:
```
ex_odd2 is
  a i64 := 0

  say (a.low32bits.castTo_i32.isZero)
```
outputs `true`, as expected. However,
```
ex_odd2 is
  a i64 := 0

  say (a.isZero)
  say (a.low32bits.castTo_i32.isZero)
```
outputs `true`, `false`.

**Comment by michaellilltokiwa** [comment]
@maxteufel but it fails in the DFA. c backend seems to work by accident.
```
error 1: java.lang.Error: check-condition failed: dev.flang.fuir.analysis.dfa.NumericValue:joinInstances:188
	at dev.flang.util.ANY.check(ANY.java:383)
	at dev.flang.fuir.analysis.dfa.NumericValue.joinInstances(NumericValue.java:188)
	at dev.flang.fuir.analysis.dfa.Value.join(Value.java:256)
	at dev.flang.fuir.analysis.dfa.Instance.setField(Instance.java:133)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:869)
	at dev.flang.fuir.analysis.dfa.DFA.iteration(DFA.java:845)
	at dev.flang.fuir.analysis.dfa.DFA.findFixPoint(DFA.java:808)
	at dev.flang.fuir.analysis.dfa.DFA.dfa(DFA.java:790)
	at dev.flang.fuir.analysis.dfa.DFA.new_fuir(DFA.java:719)
	at dev.flang.be.c.C.<init>(C.java:495)
	at dev.flang.tools.Fuzion$Backend$2.process(Fuzion.java:145)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:368)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:832)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:704)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)
```
