### ISSUE TITLE
crash when compiling loop in universe using index var 

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#112]
```
 > echo "for i in 0..1 : 1 do" | ./build/bin/fz -
java.lang.Error: check-condition3 failed!
	at dev.flang.util.ANY.check(ANY.java:411)
	at dev.flang.ast.Type.compareToIgnoreOuter(Type.java:1252)
	at dev.flang.ast.Type.compareTo(Type.java:1186)
	at dev.flang.ast.Type.compareTo(Type.java:45)
	at java.base/java.util.TreeMap.getEntry(TreeMap.java:350)
	at java.base/java.util.TreeMap.get(TreeMap.java:279)
	at dev.flang.ast.Types.intern(Types.java:284)
	at dev.flang.ast.Call.replaceGenericsInFormalArg(Call.java:1045)
	at dev.flang.ast.Call.lambda$resolveFormalArgumentTypes$2(Call.java:1111)
	at dev.flang.ast.Feature.resolveTypes(Feature.java:1426)
	at dev.flang.ast.Feature.resultTypeIfPresent(Feature.java:3397)
	at dev.flang.ast.Call.resolveTypes(Call.java:1422)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1361)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1353)
	at dev.flang.ast.Call.visit(Call.java:895)
	at dev.flang.ast.Call.visit(Call.java:893)
	at dev.flang.ast.Call.visit(Call.java:893)
	at dev.flang.ast.Call.visit(Call.java:893)
	at dev.flang.ast.Call.visit(Call.java:893)
	at dev.flang.ast.Call.visit(Call.java:49)
	at dev.flang.ast.Block.visit(Block.java:214)
	at dev.flang.ast.Block.visit(Block.java:41)
	at dev.flang.ast.Impl.visit(Impl.java:316)
	at dev.flang.ast.Feature.visit(Feature.java:1097)
	at dev.flang.ast.Feature.resolveTypes(Feature.java:1408)
	at dev.flang.ast.Feature.resultTypeIfPresent(Feature.java:3397)
	at dev.flang.ast.Call.resolveTypes(Call.java:1422)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1361)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1353)
	at dev.flang.ast.Call.visit(Call.java:895)
	at dev.flang.ast.If.visit(If.java:293)
	at dev.flang.ast.If.visit(If.java:41)
	at dev.flang.ast.Block.visit(Block.java:214)
	at dev.flang.ast.Block.visit(Block.java:41)
	at dev.flang.ast.Block.visit(Block.java:214)
	at dev.flang.ast.Block.visit(Block.java:41)
	at dev.flang.ast.Impl.visit(Impl.java:316)
	at dev.flang.ast.Feature.visit(Feature.java:1097)
	at dev.flang.ast.Feature.resolveTypes(Feature.java:1408)
	at dev.flang.ast.Resolution.resolveOne(Resolution.java:411)
	at dev.flang.ast.Resolution.resolve(Resolution.java:378)
	at dev.flang.ast.Resolution.<init>(Resolution.java:216)
	at dev.flang.fe.FrontEnd.createMIR(FrontEnd.java:155)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:471)
	at dev.flang.tools.Tool.run(Tool.java:166)
	at dev.flang.tools.Fuzion.main(Fuzion.java:209)
```
the same code within a feature `x` works fine:
```
> echo "x is for i in 0..1 : 1 do" | ./build/bin/fz -
> 
```

**Comment by fridis** [comment]
this problem has disappeared.
