### ISSUE TITLE
psMap of value type codepoint results in interpreter crash on lookup

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#115]
```
 > cat ex.fz
ex is
   x := codepoint 70
   m := psMap<codepoint, i32>.add x 42
   say "will crash: "
   m[x]
   say "not reached."
   unit
 > ./build/bin/fz ex
will crash: 

error 1: *** java.lang.ClassCastException: class dev.flang.be.interpreter.LValue cannot be cast to class dev.flang.be.interpreter.Instance (dev.flang.be.interpreter.LValue and dev.flang.be.interpreter.Instance are in unnamed module of loader 'app')
Call stack:
ref codepoint.infix >=: /home/fridi/fuzion/work/build/lib/ordered.fz:54:36:
  infix >= (other T) bool is other <= orderedThis
-----------------------------------^
ref codepoint.infix <: /home/fridi/fuzion/work/build/lib/ordered.fz:50:45:
  infix <  (other T) bool is  !(orderedThis >= other)
--------------------------------------------^
codepoint.infix <>: /home/fridi/fuzion/work/build/lib/ordered.fz:63:25:
    if      orderedThis < other then -1
------------------------^
psMap<codepoint, i32>.index [ ].binarySearch: /home/fridi/fuzion/work/build/lib/psMap.fz:179:19:
        c := (mk) <> k
------------------^
psMap<codepoint, i32>.index [ ].get: /home/fridi/fuzion/work/build/lib/psMap.fz:196:17:
          match binarySearch at at+sz-1
----------------^
psMap<codepoint, i32>.index [ ]: /home/fridi/fuzion/work/build/lib/psMap.fz:203:5:
    get 0 subSz (data.length - subSz)
----^
ex: ./ex.fz:5:5:
   m[x]
----^


java.lang.ClassCastException: class dev.flang.be.interpreter.LValue cannot be cast to class dev.flang.be.interpreter.Instance (dev.flang.be.interpreter.LValue and dev.flang.be.interpreter.Instance are in unnamed module of loader 'app')
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:279)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:326)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:293)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:326)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:849)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:749)
[...]
```

**Comment by fridis** [comment]
Here is a smaller example: 
```
 > cat ex2.fz
ex2 is
  S (v i32) ref : ordered<S> is
    infix <= (other S) bool is v <= other.v
  T : S 3 is
  p<K: ordered<K>>(k K) unit is
    _ := (k) <= k
  p T
 > ./build/bin/fz ex2
arg is lvalue[instance[ex2.p<ex2.T>]125993742@0(ex2.T)] d is dyn statis clazz is ex2.T.infix <=

error 1: *** java.lang.ClassCastException: class dev.flang.be.interpreter.LValue cannot be cast to class dev.flang.be.interpreter.Instance (dev.flang.be.interpreter.LValue and dev.flang.be.interpreter.Instance are in unnamed module of loader 'app')
Call stack:
ex2.T.infix <=: ./ex2.fz:3:43:
    infix <= (other S) bool is v <= other.v
------------------------------------------^
ex2.p<ex2.T>: ./ex2.fz:6:14:
    _ := (k) <= k
-------------^
ex2: ./ex2.fz:7:3:
  p T
--^


java.lang.ClassCastException: class dev.flang.be.interpreter.LValue cannot be cast to class dev.flang.be.interpreter.Instance (dev.flang.be.interpreter.LValue and dev.flang.be.interpreter.Instance are in unnamed module of loader 'app')
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:281)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:605)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:257)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:301)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
[...]
```
