### ISSUE TITLE
Used abstract feature 'wrapping_integer.type.all_bits_set' is not implemented by 'wrapping_integer.type'

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1179]
the example:
```
ex =>
  say (u16 18).as_bytes
```
the error:
```
$FUZION/lib/wrapping_integer.fz:31:1: error 1: Used abstract feature 'wrapping_integer.type.all_bits_set' is not implemented by 'wrapping_integer.type'
wrapping_integer(redef W type : wrapping_integer W) : integer W, wrapping_integers W is
^
Feature 'wrapping_integer.type' instantiated at $FUZION/lib/Type.fz:60:18:
  get(T type) => T
-----------------^
inherits or declares abstract feature 'wrapping_integer.type.all_bits_set' declared at $FUZION/lib/wrapping_integer.fz:213:3:
  type.all_bits_set W is abstract
--^
which is called at $FUZION/lib/wrapping_integer.fz:218:5:
    all_bits_set.ones_count / 8
----^
without providing an implementation

one error.

```
the relevant section in wrapping_integer:
```

  # this integer as an array of bytes (little endian)
  as_bytes array u8 is
    bs := (wrapping_integer W).type.byte_size
    array u8 bs (idx ->
      shift W := from_u32 (bs.as_u32-idx.as_u32-1)*8
      (wrapping_integer.this>>shift).low8bits)



  # returns the number in whose bit representation all bits are ones
  type.all_bits_set W is abstract


  # how many bytes does this integer use?
  type.byte_size i32 is
    all_bits_set.ones_count / 8
```

however with this workaround by @maxteufel it works:
```
diff --git a/lib/wrapping_integer.fz b/lib/wrapping_integer.fz
index 81e53432..42cb1a09 100644
--- a/lib/wrapping_integer.fz
+++ b/lib/wrapping_integer.fz
@@ -215,7 +215,7 @@ wrapping_integer(redef W type : wrapping_integer W) : integer W, wrapping_intege
 
   # how many bytes does this integer use?
   type.byte_size i32 is
-    all_bits_set.ones_count / 8
+    W.all_bits_set.ones_count / 8
 
```

**Comment by michaellilltokiwa** [comment]
a bit simpler even:
```
ex_abstract is
  a(T type : a T) is
    type.foo i32 is abstract

    type.bar i32 is
      foo

    baz i32 is
      (a T).type.bar

  b : a b is
    type.foo => 32

  y := b.baz
```

**Comment by michaellilltokiwa** [comment]
when using `T` instead of `(a T).type`
```
ex_abstract is
  a(T type : a T) is
    type.foo i32 is abstract

    type.bar i32 is
      foo

    baz i32 is
      T.bar

  b : a b is
    type.foo => 32

  y := b.baz
```
```
error 1: java.lang.Error: NYI: cannot find actual generic for 'ex_abstract.a.T' in heir outer clazz 'ex_abstract.b'.
	at dev.flang.air.Clazz.typeParameterActualType(Clazz.java:1987)
	at dev.flang.air.Clazz.determineResultClazz(Clazz.java:2071)
	at dev.flang.air.Clazz.dependencies(Clazz.java:415)
	at dev.flang.air.Clazzes.create(Clazzes.java:389)
	at dev.flang.air.Clazzes.clazzWithSpecificOuter(Clazzes.java:1226)
	at dev.flang.air.Clazz.lookup(Clazz.java:1142)
	at dev.flang.air.Clazzes.findClazzes(Clazzes.java:888)
	at dev.flang.air.Clazz$1.action(Clazz.java:1398)
	at dev.flang.ast.Stmnt.visitStatements(Stmnt.java:65)
	at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:112)
	at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:110)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractAssign.visitStatements(AbstractAssign.java:140)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractFeature.visitStatements(AbstractFeature.java:1388)
	at dev.flang.air.Clazz.inspectCode(Clazz.java:1348)
	at dev.flang.air.Clazz.findAllClasses(Clazz.java:1392)
	at dev.flang.air.Clazzes.findAllClasses(Clazzes.java:456)
	at dev.flang.fuir.FUIR.<init>(FUIR.java:197)
	at dev.flang.opt.Optimizer.fuir(Optimizer.java:73)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:367)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:832)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:704)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)


*** fatal errors encountered, stopping.
```

**Comment by michaellilltokiwa** [comment]
This has meanwhile been fixed.
