### ISSUE TITLE
Crash in `fixed` feature that returns outer feature's `.this`

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#1214]
An attempt to fix #141 using `fixed` causes a crash (both in interpreter and C backends):
```
matchThis is

  B is
    fixed getB option B is B.this

  match B.getB
    b B => say "got B"
    nil => say "got nil"
```
results in
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c ex_141d.fz

error 1: java.lang.Error: require-condition1 failed: dev.flang.fuir.analysis.AbstractInterpreter:pop:311
	at dev.flang.util.ANY.require(ANY.java:93)
	at dev.flang.fuir.analysis.AbstractInterpreter.pop(AbstractInterpreter.java:311)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:529)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:446)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:412)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:882)
	at dev.flang.fuir.analysis.dfa.DFA.iteration(DFA.java:847)
	at dev.flang.fuir.analysis.dfa.DFA.findFixPoint(DFA.java:810)
	at dev.flang.fuir.analysis.dfa.DFA.dfa(DFA.java:792)
	at dev.flang.fuir.analysis.dfa.DFA.new_fuir(DFA.java:721)
	at dev.flang.be.c.C.<init>(C.java:495)
	at dev.flang.tools.Fuzion$Backend$2.process(Fuzion.java:145)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:368)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:832)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:704)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)


*** fatal errors encountered, stopping.
```

**Comment by michaellilltokiwa** [comment]
does not crash anymore
