### ISSUE TITLE
Passing lazy value as argument still causes problems in the base library

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#1238]
With the following patch (and with #1234 merged!):
```diff
diff --git a/lib/list.fz b/lib/list.fz
index 4e7fbbad..8e87bf30 100644
--- a/lib/list.fz
+++ b/lib/list.fz
@@ -480,10 +480,10 @@ lists is
 # convenience routine to create a list from head h and lazy tail t.
 # NYI: #1166, syntax sugar for lazy evaluation
 #
-list(T type, h T, t () -> list T) list T is
+list(T type, h T, t Lazy (list T)) list T is
   ref : Cons T (list T)
     head => h
-    tail => t()
+    tail => t
 
 
 # convenience routine to create a list from head h and tail t.
@@ -504,6 +504,6 @@ list_of_none_lazy(T type, h T, t list T) list T is
 # or to create lists by recursion, e.g., a an endless list containing
 # integer 1 repeatedly is
 #
-#   ones => 1 : ()->ones
+#   ones => 1 : ones
 #
-infix : (A type, h A, t ()->list A) => list h t
+infix : (A type, h A, t Lazy (list A)) => list h t
```
one gets the following error during the building of `base.fum`:
```
error 1: java.lang.Error: ensure-condition failed: dev.flang.ast.AbstractFeature:findInheritanceChain:1364
	at dev.flang.util.ANY.ensure(ANY.java:236)
	at dev.flang.ast.AbstractFeature.findInheritanceChain(AbstractFeature.java:1364)
	at dev.flang.ast.AbstractFeature.handDown(AbstractFeature.java:1235)
	at dev.flang.ast.Call.handDownFormalArg(Call.java:1146)
	at dev.flang.ast.Call.lambda$resolveFormalArgumentTypes$10(Call.java:1295)
	at dev.flang.ast.Feature.internalResolveTypes(Feature.java:1328)
	at dev.flang.ast.Resolution.resolveOne(Resolution.java:371)
	at dev.flang.ast.Resolution.resolve(Resolution.java:338)
	at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:264)
	at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:178)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:830)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:704)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)


*** fatal errors encountered, stopping.
```

Building with `PRECONDITIONS=false POSTCONDITIONS=false` seems to work fine, though.

**Comment by fridis** [comment]
I am aware of this, that's why I was working on #1239
