### ISSUE TITLE
In universe: Interval applied to lambda results in check condition failure

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#124]
```
 > echo "5..0 | x -> unit" | ./build/bin/fz -
java.lang.Error: check-condition3 failed!
	at dev.flang.util.ANY.check(ANY.java:411)
	at dev.flang.ast.Type.compareToIgnoreOuter(Type.java:1252)
	at dev.flang.ast.Type.compareTo(Type.java:1186)
	at dev.flang.ast.Type.compareTo(Type.java:45)
	at java.base/java.util.TreeMap.getEntry(TreeMap.java:350)
	at java.base/java.util.TreeMap.get(TreeMap.java:279)
	at dev.flang.ast.Types.intern(Types.java:284)
	at dev.flang.ast.Types.intern(Types.java:279)
	at dev.flang.ast.Call.replaceGenericsInFormalArg(Call.java:1045)
	at dev.flang.ast.Call.lambda$resolveFormalArgumentTypes$2(Call.java:1111)
	at dev.flang.ast.Feature.whenResolvedTypes(Feature.java:1455)
	at dev.flang.ast.Call.resolveFormalArgumentTypes(Call.java:1106)
	at dev.flang.ast.Call.resolveTypes(Call.java:1454)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1365)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1357)
	at dev.flang.ast.Call.visit(Call.java:895)
	at dev.flang.ast.Call.visit(Call.java:49)
	at dev.flang.ast.Block.visit(Block.java:214)
	at dev.flang.ast.Block.visit(Block.java:41)
	at dev.flang.ast.Impl.visit(Impl.java:316)
	at dev.flang.ast.Feature.visit(Feature.java:1101)
	at dev.flang.ast.Feature.resolveTypes(Feature.java:1412)
	at dev.flang.ast.Resolution.resolveOne(Resolution.java:411)
	at dev.flang.ast.Resolution.resolve(Resolution.java:378)
	at dev.flang.ast.Resolution.<init>(Resolution.java:216)
	at dev.flang.fe.FrontEnd.createMIR(FrontEnd.java:155)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:471)
	at dev.flang.tools.Tool.run(Tool.java:166)
	at dev.flang.tools.Fuzion.main(Fuzion.java:209)

```

**Comment by fridis** [comment]
I can no longer reproduce this problem.
