### ISSUE TITLE
Interpreter precondition failure and C compilation failure in example using 'this' in inherited feature

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#125]
This small example
```
> cat crashSortedArray.fz
crashSortedArray is

  a(ia sys.array<i32>) is
   so(le (i32, i32) -> bool) => s a.this le
   sb<O: ordered<O>>(f i32 ->O) => so (a, b -> f a <= f b)

  s (f a, le (i32,i32)->bool) : a so(f, 1).internalArray is
    so(f a, hs i32) array<i32> is
      [1,2,3]

  si := s (a [1,2,3].internalArray) (x, y -> x <= y)

  si.sb<string> f->"s"

  unit
```
crashes the intepreter when preconditions are enabled:
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz crashSortedArray

error 1: *** java.lang.Error: require-condition1 failed!
Call stack:
crashSortedArray.s.so: ./crashSortedArray.fz:4:33:
   so(le (i32, i32) -> bool) => s a.this le
--------------------------------^
crashSortedArray.s.sb<string>: ./crashSortedArray.fz:5:36:
   sb<O: ordered<O>>(f i32 ->O) => so (a, b -> f a <= f b)
-----------------------------------^
crashSortedArray: ./crashSortedArray.fz:14:6:
  si.sb<string> f->"s"
-----^


java.lang.Error: require-condition1 failed!
	at dev.flang.util.ANY.require(ANY.java:66)
	at dev.flang.be.interpreter.LValue.storeNonRef(LValue.java:241)
	at dev.flang.be.interpreter.Interpreter.setNonRefField(Interpreter.java:1093)
	at dev.flang.be.interpreter.Interpreter.setFieldSlot(Interpreter.java:1291)
	at dev.flang.be.interpreter.Interpreter.setField(Interpreter.java:1317)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:830)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:780)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:313)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:357)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:324)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:357)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:880)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:780)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:313)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:357)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:324)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:357)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:880)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:780)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:313)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:357)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:880)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:780)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:223)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:484)
	at dev.flang.tools.Tool.run(Tool.java:166)
	at dev.flang.tools.Fuzion.main(Fuzion.java:209)
```
And causes error in the C frontend:
```
> PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c crashSortedArray
crashSortedArray.c:932:113: error: passing 'fzT_crashSortedArray__2s' (aka 'struct fzT_crashSortedArray__2s') to parameter of incompatible type 'fzT_crashSortedArray__1a' (aka 'struct fzT_crashSortedArray__1a')
  fzM_0 = fzC_crashSortedArray__2s(fzCur->fzF_0__H_c_crashSortedArray_o_a_o_so->fzF_0__H_c_crashSortedArray_o_a,*fzCur->fzF_0__H_c_crashSortedArray_o_a_o_so,(fzT__L4_RFunction___i32_k_i32_g*)fzCur->fzF_2_le);
                                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
crashSortedArray.c:734:107: note: passing argument to parameter 'arg0' here
fzT_crashSortedArray__2s fzC_crashSortedArray__2s(fzT_crashSortedArray* fzouter, fzT_crashSortedArray__1a arg0, fzT__L4_RFunction___i32_k_i32_g* arg1)
                                                                                                          ^
1 error generated.

error 1: C backend: C compiler failed
C compiler call 'clang -O3 -o crashSortedArray crashSortedArray.c' failed with exit code '1'

one error.
```
but works fine interpreted w/o preconditions:
```
> ./build/bin/fz crashSortedArray
>
```

**Comment by fridis** [comment]
The problem is that 'a.this' may be of a class that inherits from 'a', so it is not compatible to 'a' unless 'a' is a 'ref' type. 
Here is a smaller example:
```
 > cat cs5.fz
cs5 is

  a is
    s a.this  # 'a.this' may be of type 'b', which is not compatible to 'a'
  b : a is
  s(f a) =>

  _ := b
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz cs5

error 1: *** java.lang.Error: require-condition1 failed!
Call stack:
cs5.b: ./cs5.fz:4:5:
    s a.this  # 'a.this' may be of type 'b', which is not compatible to 'a'
----^
cs5: ./cs5.fz:8:8:
  _ := b
-------^


java.lang.Error: require-condition1 failed!
	at dev.flang.util.ANY.require(ANY.java:66)
```
