### ISSUE TITLE
NullPointerException: Cannot invoke "dev.flang.air.Clazz.isUnitType()"

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#132]
I use `unit` in a **choice type** here. I think this should not result in a NullPointerExecption.

```fuzion
binary_trees is

  node(left node|unit, right node|unit) is

  createTree(depth i32) node is
    if(depth > 0) then
      node createTree(depth - 1), createTree(depth - 1)
    else
      node node(unit, unit) unit

  depth := 10
  tree := createTree(depth)
```

```java
java.lang.NullPointerException: Cannot invoke "dev.flang.air.Clazz.isUnitType()" because the return value of "dev.flang.air.Clazz.resultClazz()" is null
        at dev.flang.air.Clazz.isUnitType(Clazz.java:674)
        at dev.flang.air.Clazz.isChoiceOfOnlyRefs(Clazz.java:1399)
        at dev.flang.air.Clazz.determineChoiceTag(Clazz.java:2013)
        at dev.flang.air.Clazz.dependencies(Clazz.java:366)
        at dev.flang.air.Clazzes.create(Clazzes.java:375)
        at dev.flang.air.Clazzes.clazzWithSpecificOuter(Clazzes.java:1157)
        at dev.flang.air.Clazz.lookup(Clazz.java:981)
        at dev.flang.air.Clazz.lookup(Clazz.java:897)
        at dev.flang.air.Clazz.determineResultClazz(Clazz.java:1811)
        at dev.flang.air.Clazz.dependencies(Clazz.java:361)
        at dev.flang.air.Clazzes.create(Clazzes.java:375)
        at dev.flang.air.Clazzes.clazzWithSpecificOuter(Clazzes.java:1157)
        at dev.flang.air.Clazz.lookup(Clazz.java:981)
        at dev.flang.air.Clazz.lookup(Clazz.java:897)
        at dev.flang.air.Clazz.determineArgumentFields(Clazz.java:1913)
        at dev.flang.air.Clazz.dependencies(Clazz.java:363)
        at dev.flang.air.Clazzes.create(Clazzes.java:375)
        at dev.flang.air.Clazzes.clazzWithSpecificOuter(Clazzes.java:1157)
        at dev.flang.air.Clazz.lookup(Clazz.java:981)
        at dev.flang.air.Clazz.lookup(Clazz.java:897)
        at dev.flang.air.Clazz.determineResultClazz(Clazz.java:1811)
        at dev.flang.air.Clazz.dependencies(Clazz.java:361)
        at dev.flang.air.Clazzes.create(Clazzes.java:375)
        at dev.flang.air.Clazzes.clazzWithSpecificOuter(Clazzes.java:1157)
        at dev.flang.air.Clazz.lookup(Clazz.java:981)
        at dev.flang.air.Clazzes.findClazzes(Clazzes.java:854)
        at dev.flang.air.Clazz$FindClassesVisitor.action(Clazz.java:1180)
        at dev.flang.air.Clazz$FindClassesVisitor.action(Clazz.java:1174)
        at dev.flang.ast.Call.visit(Call.java:871)
        at dev.flang.ast.Assign.visit(Assign.java:195)
        at dev.flang.ast.Feature$11.visit(Feature.java:1996)
        at dev.flang.ast.Feature$11.visit(Feature.java:1974)
        at dev.flang.ast.Block.visit(Block.java:214)
        at dev.flang.ast.Block.visit(Block.java:41)
        at dev.flang.ast.Block.visit(Block.java:214)
        at dev.flang.ast.Block.visit(Block.java:41)
        at dev.flang.ast.AbstractFeature.visitCode(AbstractFeature.java:665)
        at dev.flang.air.Clazz$FindClassesVisitor.visitAncestors(Clazz.java:1187)
        at dev.flang.air.Clazz.findAllClassesWhenCalled(Clazz.java:1238)
        at dev.flang.air.Clazzes.findAllClasses(Clazzes.java:431)
        at dev.flang.fuir.FUIR.<init>(FUIR.java:161)
        at dev.flang.opt.Optimizer.fuir(Optimizer.java:73)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:506)
        at dev.flang.tools.Tool.run(Tool.java:168)
        at dev.flang.tools.Fuzion.main(Fuzion.java:232)
```

**Comment by fridis** [comment]
This was fixed in patch 2374424bbde40324a74a50a356b186093524084e
