### ISSUE TITLE
`fz lib/String.fz` yields require-condition1 failed

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1358]
Max experienced the same problem in a branch of his and pointed me to this commit 510b6c2a44f62361a686e8bd4616b8775bb8b3ee which seems to introduce/uncover the issue.

```
/home/not_synced/fuzion/lib/String.fz:28:1: error 1: Duplicate feature declaration
String ref : equatable, has_hash, has_total_order is
^
Feature that was declared repeatedly: 'String'
originally declared at $FUZION/lib/String.fz:28:1:
String ref : equatable, has_hash, has_total_order is
^
To solve this, consider renaming one of these two features, e.g., as 'Stringʼ' (using a unicode modifier letter apostrophe 'ʼ' U+02BC) or adding an additional argument (e.g. '_ unit' for an ignored unit argument used only to disambiguate these two).


error 2: java.lang.Error: require-condition1 failed: dev.flang.ast.Feature:outerSet:741
	at dev.flang.util.ANY.require(ANY.java:78)
	at dev.flang.ast.Feature.outerSet(Feature.java:741)
	at dev.flang.fe.SourceModule.findDeclarations(SourceModule.java:442)
	at dev.flang.fe.SourceModule$2.action(SourceModule.java:579)
	at dev.flang.fe.SourceModule$2.action(SourceModule.java:570)
	at dev.flang.ast.Call.visit(Call.java:1052)
	at dev.flang.ast.Function.visit(Function.java:339)
	at dev.flang.ast.Call.visit(Call.java:1043)
	at dev.flang.ast.Impl.visit(Impl.java:337)
	at dev.flang.ast.Feature.visit(Feature.java:1027)
	at dev.flang.fe.SourceModule.setOuterAndAddInner(SourceModule.java:569)
	at dev.flang.fe.SourceModule.findDeclarations(SourceModule.java:450)
	at dev.flang.fe.SourceModule$2.action(SourceModule.java:584)
	at dev.flang.fe.SourceModule$2.action(SourceModule.java:570)
	at dev.flang.ast.Feature.visit(Feature.java:1875)
	at dev.flang.ast.Block.visit(Block.java:226)
	at dev.flang.ast.Block.visit(Block.java:40)
	at dev.flang.ast.Impl.visit(Impl.java:337)
	at dev.flang.ast.Feature.visit(Feature.java:1027)
	at dev.flang.fe.SourceModule.setOuterAndAddInner(SourceModule.java:569)
	at dev.flang.fe.SourceModule.findDeclarations(SourceModule.java:450)
	at dev.flang.ast.Function.propagateExpectedType2(Function.java:308)
	at dev.flang.ast.Function.propagateExpectedType(Function.java:203)
	at dev.flang.ast.Expr.wrapInLazyAndThenPropagateExpectedType(Expr.java:286)
	at dev.flang.ast.Call.propagateExpectedType(Call.java:2147)
	at dev.flang.ast.Feature$5.action(Feature.java:1672)
	at dev.flang.ast.Feature$5.action(Feature.java:1670)
	at dev.flang.ast.Call.visit(Call.java:1052)
	at dev.flang.ast.Cond.visit(Cond.java:77)
	at dev.flang.ast.Contract.visit(Contract.java:104)
	at dev.flang.ast.Feature.visit(Feature.java:1029)
	at dev.flang.ast.Feature.typeInference(Feature.java:1670)
	at dev.flang.ast.Feature.typeInference(Feature.java:1636)
	at dev.flang.ast.Resolution.resolveOne(Resolution.java:385)
	at dev.flang.ast.Resolution.resolve(Resolution.java:338)
	at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:264)
	at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:180)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:830)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)


*** fatal errors encountered, stopping.
```

**Comment by michaellilltokiwa** [comment]
update: If I comment the chained booleans in some preconditions in `String.fz` the problem disappears as well.
```
    pre
      debug: 0 ≤ from ≤ to ≤ String.this.byte_length
```
