### ISSUE TITLE
during resolveTypes(): require-condition2 failed: dev.flang.ast.Type:featureOfType:1063

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1416]
```
ex is

  private out (_ unit, _ unit) : simpleEffect is

    type.install_default =>
      (ex.out unit).default

  out =>
    out.type.install_default
    ex.out.env
```
```

error 1: java.lang.Error: require-condition2 failed: dev.flang.ast.Type:featureOfType:1063
	at dev.flang.util.ANY.require(ANY.java:94)
	at dev.flang.ast.Type.featureOfType(Type.java:1063)
	at dev.flang.ast.Feature.resultTypeRaw(Feature.java:2181)
	at dev.flang.ast.AbstractFeature.resultTypeRaw(AbstractFeature.java:957)
	at dev.flang.ast.AbstractFeature.resultTypeIfPresent(AbstractFeature.java:986)
	at dev.flang.ast.Call.resolveTypes(Call.java:2055)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1271)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1263)
	at dev.flang.ast.Call.visit(Call.java:1033)
	at dev.flang.ast.Call.visit(Call.java:47)
	at dev.flang.ast.Block.visit(Block.java:226)
	at dev.flang.ast.Block.visit(Block.java:40)
	at dev.flang.ast.Call.visit(Call.java:1030)
	at dev.flang.ast.Call.visit(Call.java:47)
	at dev.flang.ast.Block.visit(Block.java:226)
	at dev.flang.ast.Block.visit(Block.java:40)
	at dev.flang.ast.Impl.visit(Impl.java:337)
	at dev.flang.ast.Feature.visit(Feature.java:1027)
	at dev.flang.ast.Feature.internalResolveTypes(Feature.java:1309)
	at dev.flang.ast.Resolution.resolveTypes(Resolution.java:461)
	at dev.flang.ast.AbstractFeature.resultTypeIfPresent(AbstractFeature.java:984)
	at dev.flang.ast.Call.resolveTypes(Call.java:2055)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1271)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1263)
	at dev.flang.ast.Call.visit(Call.java:1033)
	at dev.flang.ast.Call.visit(Call.java:47)
	at dev.flang.ast.Block.visit(Block.java:226)
	at dev.flang.ast.Block.visit(Block.java:40)
	at dev.flang.ast.Impl.visit(Impl.java:337)
	at dev.flang.ast.Feature.visit(Feature.java:1027)
	at dev.flang.ast.Feature.internalResolveTypes(Feature.java:1309)
	at dev.flang.ast.Resolution.resolveOne(Resolution.java:371)
	at dev.flang.ast.Resolution.resolve(Resolution.java:338)
	at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:259)
	at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:181)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:830)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)


*** fatal errors encountered, stopping.
```

**Comment by michaellilltokiwa** [comment]
seems solved.
