### ISSUE TITLE
precondition failure when calling abstract type feature

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#1461]
This small example derived from the example of #1294
```
fs b

a(T type) is
  type.zero T is abstract

b : a bool is

fs(F type : a F) =>
  _ := F.zero
  unit
```
results in a precondition failure:
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c ex1294b.fz 

error 1: java.lang.Error: require-condition1 failed: dev.flang.air.Clazzes:clazz:1213
	at dev.flang.util.ANY.require(ANY.java:93)
	at dev.flang.air.Clazzes.clazz(Clazzes.java:1213)
	at dev.flang.air.Clazz.actualClazz(Clazz.java:667)
	at dev.flang.air.Clazz.determineResultClazz(Clazz.java:2356)
	at dev.flang.air.Clazz.dependencies(Clazz.java:414)
	at dev.flang.air.Clazzes.create(Clazzes.java:380)
	at dev.flang.air.Clazzes.clazzWithSpecificOuter(Clazzes.java:1263)
	at dev.flang.air.Clazz.lookup(Clazz.java:1298)
	at dev.flang.air.Clazz.lookup(Clazz.java:1065)
	at dev.flang.air.Clazzes.findClazzes(Clazzes.java:751)
	at dev.flang.air.Clazz$1.action(Clazz.java:1564)
	at dev.flang.ast.Stmnt.visitStatements(Stmnt.java:65)
	at dev.flang.ast.AbstractAssign.visitStatements(AbstractAssign.java:142)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractAssign.visitStatements(AbstractAssign.java:140)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractFeature.visitStatements(AbstractFeature.java:1449)
	at dev.flang.air.Clazz.inspectCode(Clazz.java:1515)
	at dev.flang.air.Clazz.findAllClasses(Clazz.java:1559)
	at dev.flang.air.Clazzes.findAllClasses(Clazzes.java:444)
	at dev.flang.fuir.FUIR.<init>(FUIR.java:199)
	at dev.flang.opt.Optimizer.fuir(Optimizer.java:73)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:380)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:845)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:494)


*** fatal errors encountered, stopping.
```

**Comment by fridis** [comment]
Here is a slightly simpler example
```
fs (a i32)

a(T type) is
  type.zero T is abstract

fs(F type : a F) =>
  xyz := F.zero
```
that causes the same problem
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz ex1294b.fz 

error 1: java.lang.Error: require-condition1 failed: dev.flang.air.Clazzes:clazz:1213
	at dev.flang.util.ANY.require(ANY.java:93)
	at dev.flang.air.Clazzes.clazz(Clazzes.java:1213)
	at dev.flang.air.Clazz.actualClazz(Clazz.java:668)
	at dev.flang.air.Clazz.determineResultClazz(Clazz.java:2365)
	at dev.flang.air.Clazz.dependencies(Clazz.java:414)
	at dev.flang.air.Clazzes.create(Clazzes.java:380)
	at dev.flang.air.Clazzes.clazzWithSpecificOuter(Clazzes.java:1263)
	at dev.flang.air.Clazz.lookup(Clazz.java:1303)
	at dev.flang.air.Clazz.lookup(Clazz.java:1070)
	at dev.flang.air.Clazzes.findClazzes(Clazzes.java:751)
	at dev.flang.air.Clazz$1.action(Clazz.java:1569)
	at dev.flang.ast.Stmnt.visitStatements(Stmnt.java:65)
	at dev.flang.ast.AbstractAssign.visitStatements(AbstractAssign.java:142)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractAssign.visitStatements(AbstractAssign.java:140)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractFeature.visitStatements(AbstractFeature.java:1449)
	at dev.flang.air.Clazz.inspectCode(Clazz.java:1520)
	at dev.flang.air.Clazz.findAllClasses(Clazz.java:1564)
	at dev.flang.air.Clazzes.findAllClasses(Clazzes.java:444)
	at dev.flang.fuir.FUIR.<init>(FUIR.java:199)
	at dev.flang.opt.Optimizer.fuir(Optimizer.java:73)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:380)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:845)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:494)


*** fatal errors encountered, stopping.
```
