### ISSUE TITLE
Small example using lazy and recursion results in DFA error

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#1665]
This small example
```
l(t Lazy l) is
  n => t.n

f => l (l f)
f.n
```
produces this internal error during DFA:
```
 > ./build/bin/fz -c fib_zip7.fz  -o=fibzip

/home/fridi/fuzion/clean/fuzion.1/fib_zip7.fz:4:11: error 1: NYI: in (f.ref #fun1).call no targets for Call to f.ref #fun0 target (f.ref #fun1).call
f => l (l f)
----------^

one error.

```

**Comment by fridis** [comment]
This is a problem in the front end that triggers a postcondition failure: 
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c fib_zip7.fz 

error 1: java.lang.Error: ensure-condition failed: dev.flang.ast.AbstractFeature:findInheritanceChain:1371
	at dev.flang.util.ANY.ensure(ANY.java:236)
	at dev.flang.ast.AbstractFeature.findInheritanceChain(AbstractFeature.java:1371)
	at dev.flang.air.Clazz.findRedefinition(Clazz.java:1016)
	at dev.flang.air.Clazz.lookup(Clazz.java:1188)
	at dev.flang.air.Clazzes.findClazzes(Clazzes.java:914)
	at dev.flang.air.Clazz$1.action(Clazz.java:1572)
	at dev.flang.ast.Stmnt.visitStatements(Stmnt.java:65)
	at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:112)
	at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:106)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:99)
	at dev.flang.ast.AbstractAssign.visitStatements(AbstractAssign.java:139)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:99)
	at dev.flang.ast.AbstractFeature.visitStatements(AbstractFeature.java:1463)
	at dev.flang.air.Clazz.inspectCode(Clazz.java:1522)
	at dev.flang.air.Clazz.findAllClasses(Clazz.java:1566)
	at dev.flang.air.Clazzes.findAllClasses(Clazzes.java:444)
	at dev.flang.fuir.FUIR.<init>(FUIR.java:199)
	at dev.flang.opt.Optimizer.fuir(Optimizer.java:73)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:405)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:870)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:519)


*** fatal errors encountered, stopping.

```
