### ISSUE TITLE
Small example using `void` type as arg to `Lazy` results in error class or crash

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#1666]
This example
```
l(t Lazy l) is
  n => t

f l is l (do)
_ := f.n
```
results in an error when using DFA
```
 > ./build/bin/fz -c -Xdfa=on ex_1665b.fz 

error 1: Found error clazz in set of clazzes in the IR even though no earlier errors were reported.  This can only be the result of a severe bug.

one error.
```
and results in a crash when not using DFA
```
 > ./build/bin/fz -c -Xdfa=off ex_1665b.fz 

error 1: Found error clazz in set of clazzes in the IR even though no earlier errors were reported.  This can only be the result of a severe bug.


error 2: java.lang.IndexOutOfBoundsException: Index -268435457 out of bounds for length 95
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at dev.flang.util.Map2Int.get(Map2Int.java:148)
	at dev.flang.fuir.FUIR.clazz(FUIR.java:236)
	at dev.flang.fuir.FUIR.clazzArgCount(FUIR.java:599)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:603)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:480)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:446)
	at dev.flang.be.c.C.codeForRoutine(C.java:1368)
	at dev.flang.be.c.C.code(C.java:1336)
	at dev.flang.be.c.C$CompilePhase$4.compile(C.java:420)
	at dev.flang.be.c.C.lambda$createCode$4(C.java:693)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
	at dev.flang.be.c.C.createCode(C.java:689)
	at dev.flang.be.c.C.compile(C.java:520)
	at dev.flang.tools.Fuzion$Backend$2.process(Fuzion.java:148)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:406)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:870)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:519)


*** fatal errors encountered, stopping.
```

This is related to #1665.

**Comment by fridis** [comment]
The problem is that the loop `do` expands to the declaration of some inner features for which `SourceModule.findDeclarations` get called twice, resulting in a crash during the front end phase when precondition checking is enabled. Here is a smaller example declaring feature `x` assigned to a lazy value: 
```
l(t Lazy i32) is
l ({
     x is
   })
```
results in
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c -Xdfa=on ex_1665c.fz 

error 1: java.lang.Error: require-condition1 failed: dev.flang.ast.Feature:outerSet:741
	at dev.flang.util.ANY.require(ANY.java:78)
	at dev.flang.ast.Feature.outerSet(Feature.java:741)
	at dev.flang.fe.SourceModule.findDeclarations(SourceModule.java:444)
	at dev.flang.fe.SourceModule$2.action(SourceModule.java:588)
	at dev.flang.fe.SourceModule$2.action(SourceModule.java:572)
	at dev.flang.ast.Feature.visit(Feature.java:1866)
	at dev.flang.ast.Block.visit(Block.java:226)
	at dev.flang.ast.Block.visit(Block.java:40)
	at dev.flang.ast.Block.visit(Block.java:226)
	at dev.flang.ast.Block.visit(Block.java:40)
	at dev.flang.ast.Impl.visit(Impl.java:341)
	at dev.flang.ast.Feature.visit(Feature.java:1011)
```
