### ISSUE TITLE
Attempt to create short-hand for effect environment creates new instance

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#1698]
Attempting to do the following:
```
ex is
  x := try (()->
    t := try.env
    t.raise (error "a"))
  say x
```
creates a second instance of the try effect, which causes a precondition failure on raise. This works:
```
ex is
  x := try (()->
    try.env.raise (error "a"))
  say x
```

**Comment by michaellilltokiwa** [comment]
updated:
```
/home/not_synced/fuzion (2024-02-21T09-36-51+01-00)1$ cat ~/playground/test.fz
# ex =>
#   a := [1,2,3]
#     .flat_map (x -> [codepoint 35])


ex is
  x := try unit void ()->
    t := (try unit).env
    t.raise (error "a")
  say x
/home/not_synced/fuzion (2024-02-21T09-36-51+01-00)$ fz ~/playground/test.fz 

error 1: java.lang.Error: require-condition2 failed: dev.flang.air.Clazz:actualClazzes:1628
        at dev.flang.util.ANY.require(ANY.java:100)
        at dev.flang.air.Clazz.actualClazzes(Clazz.java:1628)
        at dev.flang.fuir.FUIR.accessedClazz(FUIR.java:1484)
        at dev.flang.fuir.cfg.CFG.createCallGraphForExpr(CFG.java:572)
        at dev.flang.fuir.cfg.CFG.createCallGraphForBlock(CFG.java:546)
        at dev.flang.fuir.cfg.CFG.createCallGraphForExpr(CFG.java:590)
        at dev.flang.fuir.cfg.CFG.createCallGraphForBlock(CFG.java:546)
        at dev.flang.fuir.cfg.CFG.createCallGraphForRoutine(CFG.java:191)
        at dev.flang.fuir.cfg.CFG.createCallGraph(CFG.java:161)
        at dev.flang.fuir.cfg.CFG.createCallGraph(CFG.java:143)
        at dev.flang.be.effects.Effects.<init>(Effects.java:82)
        at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:455)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:920)
        at dev.flang.tools.Tool.lambda$run$0(Tool.java:140)
        at dev.flang.util.Errors.runAndExit(Errors.java:878)
        at dev.flang.tools.Tool.run(Tool.java:140)
        at dev.flang.tools.Fuzion.main(Fuzion.java:569)


*** fatal errors encountered, stopping.
```
