### ISSUE TITLE
unhandled dynamic target in access of (ref Any).as_string

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#1750]
Works:
```
ex_c_string is
  a := fuzion.sys.c_string "example"

  say a.as_string
```
output:
```
instance[ref Any]
```

But this does not work:
```
ex_c_string2 is
  a := fuzion.sys.c_string "example"

  say a
```
output:
```
*** ex_c_string2.c:11193: unhandled dynamic target 1835104357 in access of (ref Any).as_string within fuzion.sys.out.print
```

Additionally, both examples crash the interpreter:
```
error 1: *** java.lang.ClassCastException: class dev.flang.be.interpreter.ArrayData cannot be cast to class dev.flang.be.interpreter.ValueWithClazz (dev.flang.be.interpreter.ArrayData and dev.flang.be.interpreter.ValueWithClazz are in unnamed module of loader 'app')
Call stack:
ex_c_string: ex_c_string.fz:4:9:
  say a.as_string
--------^^^^^^^^^



error 2: java.lang.ClassCastException: class dev.flang.be.interpreter.ArrayData cannot be cast to class dev.flang.be.interpreter.ValueWithClazz (dev.flang.be.interpreter.ArrayData and dev.flang.be.interpreter.ValueWithClazz are in unnamed module of loader 'app')
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:326)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:620)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:297)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:388)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:903)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:779)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:228)
	at dev.flang.tools.Fuzion$Backend$1.process(Fuzion.java:106)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:406)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:870)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:156)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:156)
	at dev.flang.tools.Fuzion.main(Fuzion.java:519)


*** fatal errors encountered, stopping.
```

```
error 1: *** java.lang.ClassCastException: class dev.flang.be.interpreter.ArrayData cannot be cast to class dev.flang.be.interpreter.ValueWithClazz (dev.flang.be.interpreter.ArrayData and dev.flang.be.interpreter.ValueWithClazz are in unnamed module of loader 'app')
Call stack:
fuzion.sys.out.print: $FUZION/lib/fuzion/sys/out.fz:31:13:
    write s.as_string.utf8.as_array
------------^
(((io.#type io).out.#type io.out).default_print_handler).print: $FUZION/lib/io/out.fz:36:36:
    print(s Any) => fuzion.sys.out.print s
-----------------------------------^
(((io.#type io).out.#type io.out).default_print_handler).println: $FUZION/lib/io/print_effect.fz:55:5:
    print s
----^
io.out.println: $FUZION/lib/io/print_effect.fz:36:7:
    p.println s
------^
say: $FUZION/lib/say.fz:31:29:
public say(s Any) => io.out.println s
----------------------------^
ex_c_string2: ex_c_string2.fz:4:3:
  say a
--^^^



error 2: java.lang.ClassCastException: class dev.flang.be.interpreter.ArrayData cannot be cast to class dev.flang.be.interpreter.ValueWithClazz (dev.flang.be.interpreter.ArrayData and dev.flang.be.interpreter.ValueWithClazz are in unnamed module of loader 'app')
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:326)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:615)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:297)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:615)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:297)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:620)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:297)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:343)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:388)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:903)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:779)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:332)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:343)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:388)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:903)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:779)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:332)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:388)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:615)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:297)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:615)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:297)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:343)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:388)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:903)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:779)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:332)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:388)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:615)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:297)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:507)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:615)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:297)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:343)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:388)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:903)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:779)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:332)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:343)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:388)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:903)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:779)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:332)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:388)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:903)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:779)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:228)
	at dev.flang.tools.Fuzion$Backend$1.process(Fuzion.java:106)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:406)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:870)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:156)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:156)
	at dev.flang.tools.Fuzion.main(Fuzion.java:519)


*** fatal errors encountered, stopping.
```

**Comment by michaellilltokiwa** [comment]
I think it is okay this crashes since `as_string` is essentially called on a pointer. With correct visibility it should not be possible to trigger this crash.
