### ISSUE TITLE
Curry's paradox leads to clang error in c backend

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1777]
Taken from: https://counterexamples.org/currys-paradox.html

```
ex is
  Curry ref is
    r(x Curry) i32 is abstract

  my_loop i32 is
    c := (ref : Curry
      r(x Curry) => x.r x
    )
    c.r c

  _ := my_loop
```
```
error 1: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at dev.flang.be.c.C.tailRecursion(C.java:1198)
	at dev.flang.be.c.C.call(C.java:1119)
	at dev.flang.be.c.C.access(C.java:901)
	at dev.flang.be.c.C$CodeGen.call(C.java:177)
	at dev.flang.be.c.C$CodeGen.call(C.java:62)
...
```

**Comment by michaellilltokiwa** [comment]
update: 
```
ex is
  Curry ref is
    r(x Curry) i32 => abstract

  my_loop i32 =>
    c := (ref : Curry
      r(x Curry) => x.r x
    )
    c.r c

  _ := my_loop
```

**Comment by michaellilltokiwa** [comment]
see also: #3056

**Comment by michaellilltokiwa** [comment]
```
/tmp/fuzion_ex_12076878201904451167.c:101:75: error: parameter 'fzouter' set but not used [-Werror,-Wunused-but-set-parameter]
fzT_1i32 fzC__L36ex__my_u_l__nymous0__1r(fzT_ex__my_u_loop_R_Hanonymous0* fzouter, fzT_ex_RCurry* arg0)
                                                                          ^
1 error generated.

error 1: C backend: C compiler failed
C compiler call 'clang --target=x86_64-pc-linux-gnu -ftrapv -Wall -Werror -Wextra -Wpedantic -Wformat=2 -Wno-unused-parameter -Wshadow -Wwrite-strings -Wold-style-definition -Wredundant-decls -Wnested-externs -Wmissing-include-dirs -Wno-strict-prototypes -Wno-gnu-empty-initializer -Wno-zero-length-array -Wno-trigraphs -Wno-gnu-empty-struct -Wno-unused-variable -Wno-unused-label -Wno-unused-function -Wno-pointer-to-int-cast -Wno-missing-include-dirs -Wno-infinite-recursion -Wno-unused-but-set-variable -O3 -DGC_THREADS -DGC_PTHREADS -DPTW32_STATIC_LIB -DGC_WIN32_PTHREADS -fno-trigraphs -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -std=c11 -o ex /home/not_synced/fuzion/build/include/shared.c /home/not_synced/fuzion/build/include/posix.c /tmp/fuzion_ex_12076878201904451167.c -lgc' failed with exit code '1'

one error.

```
