### ISSUE TITLE
NullPointerException: Cannot read field "_outer" because "<local5>" is null

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#179]
When trying to run `fz ex.fz` of the patch below a NullPointerException occurs.
```patch
diff --git a/ex.fz b/ex.fz
new file mode 100644
index 00000000..1cb30254
--- /dev/null
+++ b/ex.fz
@@ -0,0 +1,2 @@
+ex is
+  b
diff --git a/lib/b.fz b/lib/b.fz
new file mode 100644
index 00000000..4c676de4
--- /dev/null
+++ b/lib/b.fz
@@ -0,0 +1,2 @@
+b : fuzion.std.out =>
+  println "hello"
```
```java
java.lang.NullPointerException: Cannot invoke "dev.flang.air.Clazz.feature()" because "<local5>" is null
        at dev.flang.air.Clazz.determineResultClazz(Clazz.java:1814)
        at dev.flang.air.Clazz.dependencies(Clazz.java:362)
        at dev.flang.air.Clazzes.create(Clazzes.java:363)
        at dev.flang.air.Clazzes.clazzWithSpecificOuter(Clazzes.java:1144)
        at dev.flang.air.Clazz.lookup(Clazz.java:984)
        at dev.flang.air.Clazzes.findClazzes(Clazzes.java:824)
        at dev.flang.air.Clazz$1.action(Clazz.java:1227)
        at dev.flang.ast.Stmnt.visitStatements(Stmnt.java:72)
        at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:124)
        at dev.flang.ast.AbstractAssign.visitStatements(AbstractAssign.java:140)
        at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
        at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:122)
        at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
        at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:118)
        at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
        at dev.flang.ast.AbstractAssign.visitStatements(AbstractAssign.java:140)
        at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
        at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:122)
        at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
        at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:122)
        at dev.flang.ast.AbstractAssign.visitStatements(AbstractAssign.java:140)
        at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
        at dev.flang.ast.AbstractFeature.visitStatements(AbstractFeature.java:935)
        at dev.flang.air.Clazz.inspectCode(Clazz.java:1179)
        at dev.flang.air.Clazz.findAllClasses(Clazz.java:1221)
        at dev.flang.air.Clazzes.findAllClasses(Clazzes.java:419)
        at dev.flang.fuir.FUIR.<init>(FUIR.java:155)
        at dev.flang.opt.Optimizer.fuir(Optimizer.java:73)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:540)
        at dev.flang.tools.Tool.run(Tool.java:168)
        at dev.flang.tools.Fuzion.main(Fuzion.java:244)
```

**Comment by fridis** [comment]
I can no longer reproduce this, maybe fixed this meanwhile.

**Comment by michaellilltokiwa** [comment]
seems fixed.
