### ISSUE TITLE
require condition failed: dev.flang.be.interpreter.Layout:sizeAvailable

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1799]
```
main is
  my_effect : effect effect_mode.plain
  is

    private err option error := nil

    public on(R type, f ()->R) outcome R is
      res option R := nil
      abortable (Function unit) (()->set res := f(); unit)
      res.get


    public raise(e error) =>
      set err := e
      abort

  say (my_effect.on (() -> my_effect.env.abort))
```
```

error 1: *** java.lang.Error: require-condition1 failed: dev.flang.be.interpreter.Layout:sizeAvailable:202
Call stack:
main.my_effect.on void: /home/sam/playground/test.fz:9:7:
      abortable (Function unit) (()->set res := f(); unit)
------^^^^^^^^^
main: /home/sam/playground/test.fz:17:18:
  say (my_effect.on (() -> my_effect.env.abort))
-----------------^^



error 2: java.lang.Error: require-condition1 failed: dev.flang.be.interpreter.Layout:sizeAvailable:202
	at dev.flang.util.ANY.require(ANY.java:78)
	at dev.flang.be.interpreter.Layout.sizeAvailable(Layout.java:202)
	at dev.flang.be.interpreter.Layout.size(Layout.java:214)
	at dev.flang.be.interpreter.Instance.<init>(Instance.java:90)
	at dev.flang.be.interpreter.Intrinsics.lambda$effect$541(Intrinsics.java:1314)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:332)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:388)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:343)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:388)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:905)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:781)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:332)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:525)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:388)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:620)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:297)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:388)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:905)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:781)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:228)
	at dev.flang.tools.Fuzion$Backend$1.process(Fuzion.java:106)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:406)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:870)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:156)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:156)
	at dev.flang.tools.Fuzion.main(Fuzion.java:519)


*** fatal errors encountered, stopping.

```

**Comment by michaellilltokiwa** [comment]
closing, due to new interpreter
