### ISSUE TITLE
check-condition failure in `ResolvedParametricType.generics()`

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#1811]
Applying this diff
```diff
diff --git a/lib/Function.fz b/lib/Function.fz
index 828c1148..bfd2ef68 100644
--- a/lib/Function.fz
+++ b/lib/Function.fz
@@ -27,11 +27,11 @@
 #
 # R is the result type of the function, A are the argument types of the function
 #
-public Function(R type, A type...) ref is
+public Function(R type, FA type...) ref is
 
   # call this function on given arguments A...
   #
-  public call(a A) R is abstract
+  public call(a FA) R is abstract
 
 
 # NYI: would be nice to have schönfinkeling defined here, could work like this:
diff --git a/lib/Lazy.fz b/lib/Lazy.fz
index 7d094a84..fec420ca 100644
--- a/lib/Lazy.fz
+++ b/lib/Lazy.fz
@@ -23,4 +23,17 @@
 
 # Lazy
 #
-public Lazy(T type) ref : Function T is
+public Lazy(T type) ref : Function T, monad T (Lazy T) is
+
+  # monadic operator
+  #
+  public bind(B type, f T -> Lazy B) Lazy B is
+    v := call
+    (() ->
+      application Lazy B := f v
+      application)
+
+
+  # return function
+  #
+  public fixed type.return (a T) Lazy T is () -> a
```
leads to the following error when doing `make no-java`:
```
error 1: java.lang.Error: check-condition failed: dev.flang.ast.ResolvedParametricType:generics:147
	at dev.flang.util.ANY.check(ANY.java:383)
	at dev.flang.ast.ResolvedParametricType.generics(ResolvedParametricType.java:147)
	at dev.flang.ast.Call.resolveFormalArg(Call.java:1281)
	at dev.flang.ast.Call.lambda$resolveFormalArgumentTypes$11(Call.java:1354)
	at dev.flang.ast.Feature.internalResolveTypes(Feature.java:1349)
	at dev.flang.ast.Resolution.resolveOne(Resolution.java:371)
	at dev.flang.ast.Resolution.resolve(Resolution.java:338)
	at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:258)
	at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:183)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:868)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:156)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:156)
	at dev.flang.tools.Fuzion.main(Fuzion.java:519)
```
disabling pre and postconditions makes this work.

**Comment by michaellilltokiwa** [comment]
```
diff --git a/lib/Function.fz b/lib/Function.fz
index d0400cca4..b0c7216a1 100644
--- a/lib/Function.fz
+++ b/lib/Function.fz
@@ -27,12 +27,11 @@
 #
 # R is the result type of the function, A are the argument types of the function
 #
-public Function(public R type,
-                public A type...) ref is
+public Function(public R type, public FA type...) ref is
 
   # call this function on given arguments a...
   #
-  public call(a A) R => abstract
+  public call(a FA) R => abstract
 
 
 # NYI: would be nice to have sch��nfinkeling defined here, could work like this:
diff --git a/lib/Lazy.fz b/lib/Lazy.fz
index fb2efa104..7ee003d16 100644
--- a/lib/Lazy.fz
+++ b/lib/Lazy.fz
@@ -31,4 +31,17 @@
 # `4+5>10` will never be executed:
 #     true || 4+5>10
 #
-public Lazy(public T type) ref : Function T is
+public Lazy(public T type) ref : Function T, monad T (Lazy T) is
+
+  # monadic operator
+  #
+  public bind(B type, f T -> Lazy B) Lazy B =>
+    v := call
+    (() ->
+      application Lazy B := f v
+      application)
+
+
+  # return function
+  #
+  public redef fixed type.return (a T) Lazy T => () -> a

```

seems, no longer a problem
