### ISSUE TITLE
Small test with precondition results in EmptyStackException

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#1838]
Using this example 
```
test_pre is

 x(bool c) unit
 pre c
 is
   say "x $c"

 x true
 x false
```
the C backend crashes
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c test_pre.fz 

error 1: java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:101)
	at java.base/java.util.Stack.pop(Stack.java:83)
	at dev.flang.fuir.analysis.AbstractInterpreter.processContract(AbstractInterpreter.java:513)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:445)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1050)
	at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:1817)
	at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:1779)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:374)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:235)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:82)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:606)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:480)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:446)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1050)
	at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:1817)
	at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:1779)
	at dev.flang.fuir.analysis.dfa.DFA.dfa(DFA.java:953)
	at dev.flang.fuir.analysis.dfa.DFA.new_fuir(DFA.java:815)
	at dev.flang.be.c.C.<init>(C.java:498)
	at dev.flang.tools.Fuzion$Backend$2.process(Fuzion.java:148)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:406)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:870)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:156)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:156)
	at dev.flang.tools.Fuzion.main(Fuzion.java:519)


*** fatal errors encountered, stopping.
```
the interpreter backend works fine:
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz test_pre.fz 

error 1: *** java.lang.Error: require-condition1 failed: dev.flang.be.interpreter.Instance:boolValue:318
Call stack:
test_pre: /home/fridi/fuzion/work/../clean/fuzion.2/test_pre.fz:8:2:
 x true
-^



error 2: java.lang.Error: require-condition1 failed: dev.flang.be.interpreter.Instance:boolValue:318
	at dev.flang.util.ANY.require(ANY.java:78)
	at dev.flang.be.interpreter.Instance.boolValue(Instance.java:318)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:881)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:781)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:332)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:388)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:905)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:781)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:228)
	at dev.flang.tools.Fuzion$Backend$1.process(Fuzion.java:106)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:406)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:870)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:156)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:156)
	at dev.flang.tools.Fuzion.main(Fuzion.java:519)


*** fatal errors encountered, stopping.

```

**Comment by michaellilltokiwa** [comment]
This example should probably not get past the frontend. Argument type and name seem mixed up?
