### ISSUE TITLE
Small example using `nil` and `type_of` crashes interpreter and DFA

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#1863]
```
b := (String.type.from_marray ((marray Any).type.new 1 nil))
say (type_of b)
```
 > ../../bin/fz t.fz

error 1: *** java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
Call stack:
(ref Type).as_string: $FUZION/lib/Type.fz:46:40:
  public redef as_string => "Type of '$name'"
---------------------------------------^
(((io.#type io).out.#type io.out).default_print_handler).println: $FUZION/lib/io/print_effect.fz:55:14:
    print (s.as_string + (codepoint 10))
-------------^
io.out.println: $FUZION/lib/io/print_effect.fz:36:7:
    p.println s
------^
say: $FUZION/lib/say.fz:31:29:
public say(s Any) => io.out.println s
----------------------------^
universe#0: /home/fridi/fuzion/work/build/tests/lib_string/t.fz:2:1:
say (type_of b)
^^^

error 2: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at dev.flang.air.Clazz.typeName(Clazz.java:2119)
	at dev.flang.be.interpreter.Intrinsics.lambda$static$3(Intrinsics.java:246)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:331)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:619)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:614)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:342)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:387)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:904)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:780)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:331)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:614)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:619)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:342)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:387)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:904)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:780)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:331)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:387)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:614)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:506)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:614)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:342)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:387)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:904)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:780)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:331)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:342)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:387)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:904)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:780)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:331)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:387)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:904)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$5(Interpreter.java:776)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:227)
	at dev.flang.tools.Fuzion$Backend$1.process(Fuzion.java:106)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:426)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:890)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:156)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:156)
	at dev.flang.tools.Fuzion.main(Fuzion.java:539)

*** fatal errors encountered, stopping.
```
```
 > ../../bin/fz -c t.fz

error 1: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at dev.flang.air.Clazz.typeName(Clazz.java:2119)
	at dev.flang.fuir.FUIR.clazzTypeName(FUIR.java:515)
	at dev.flang.fuir.analysis.dfa.DFA.lambda$static$2(DFA.java:1163)
	at dev.flang.fuir.analysis.dfa.Call.result(Call.java:210)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:375)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:320)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$1(DFA.java:281)
	at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:353)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:273)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:239)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:82)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:627)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:500)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:466)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1050)
	at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:1817)
	at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:1779)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:374)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:320)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$1(DFA.java:281)
	at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:353)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:273)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:239)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:82)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:627)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:500)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:466)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1050)
	at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:1817)
	at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:1779)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:374)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:320)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$1(DFA.java:281)
	at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:353)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:273)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:239)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:82)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:627)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:500)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:466)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1050)
	at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:1817)
	at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:1779)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:374)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:320)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$1(DFA.java:281)
	at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:353)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:273)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:239)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:82)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:627)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:500)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:466)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1050)
	at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:1817)
	at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:1779)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:374)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:320)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$1(DFA.java:281)
	at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:353)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:273)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:239)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:82)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:627)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:500)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:466)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1050)
	at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:1817)
	at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:1779)
	at dev.flang.fuir.analysis.dfa.DFA.dfa(DFA.java:953)
	at dev.flang.fuir.analysis.dfa.DFA.new_fuir(DFA.java:815)
	at dev.flang.be.c.C.<init>(C.java:498)
	at dev.flang.tools.Fuzion$Backend$2.process(Fuzion.java:148)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:426)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:890)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:156)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:156)
	at dev.flang.tools.Fuzion.main(Fuzion.java:539)

*** fatal errors encountered, stopping.

```

**Comment by michaellilltokiwa** [comment]
fails with different error now. same error as #1862 thus closing as duplicate.
