### ISSUE TITLE
be/jvm: wrong result

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1914]
example extracted from test `outerNormalization`:
```
ex is

  a (i i32) ref is
    f is
      set i := i+1
      s := i

  b : a 3 is
  c : a 4 is

  call_f (v a) unit is
    say "testConstructor: {v.f.s}"

  call_f b
  call_f c
```
yields:
```
testConstructor: 3
testConstructor: 4
```
in interpreter and c-backend it is correct:
```
testConstructor: 4
testConstructor: 5
```

**Comment by michaellilltokiwa** [comment]
now yields an error:
```

error 1: java.lang.Error: check-condition failed: dev.flang.be.jvm.CodeGen:assign:257
        at dev.flang.util.ANY.check(ANY.java:383)
        at dev.flang.be.jvm.CodeGen.assign(CodeGen.java:257)
        at dev.flang.be.jvm.CodeGen.assign(CodeGen.java:51)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:600)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:495)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:460)
        at dev.flang.be.jvm.JVM.codeForRoutine(JVM.java:1073)
        at dev.flang.be.jvm.JVM.code(JVM.java:813)
        at dev.flang.be.jvm.JVM$CompilePhase$3.compile(JVM.java:456)
        at dev.flang.be.jvm.JVM.lambda$createCode$0(JVM.java:787)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
        at dev.flang.be.jvm.JVM.createCode(JVM.java:780)
        at dev.flang.be.jvm.JVM.compile(JVM.java:765)
        at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:163)
        at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:444)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:908)
        at dev.flang.tools.Tool.lambda$run$0(Tool.java:145)
        at dev.flang.util.Errors.runAndExit(Errors.java:762)
        at dev.flang.tools.Tool.run(Tool.java:145)
        at dev.flang.tools.Fuzion.main(Fuzion.java:557)


*** fatal errors encountered, stopping.
```
