### ISSUE TITLE
Changing the `safety` intrinsic uncovers NullPointerException in JVM classes

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#1955]
Applying the following patch (alternatively you can use #1954):
```diff
diff --git a/src/dev/flang/be/jvm/runtime/Intrinsics.java b/src/dev/flang/be/jvm/runtime/Intrinsics.java
index e42c50a6..ef749c52 100644
--- a/src/dev/flang/be/jvm/runtime/Intrinsics.java
+++ b/src/dev/flang/be/jvm/runtime/Intrinsics.java
@@ -42,7 +42,7 @@ public class Intrinsics extends ANY
   /*-------------------------  static methods  --------------------------*/
 
 
-  public static boolean safety      () { return true; /* NYI: Interpreter._options_.fuzionSafety()     */ }
+  public static boolean safety      () { return false; /* NYI: Interpreter._options_.fuzionSafety()     */ }
   public static boolean debug       () { return true; /* NYI: Interpreter._options_.fuzionDebug()      */ }
   public static int     debug_level () { return 0;    /* NYI: Interpreter._options_.fuzionDebugLevel() */ }
```
and using the following test program:
```
levels =>
  say safety
  say debug
  say debug_level
```
compiled and started with
```
$ fz -classes levels.fz
$ java -classpath ./build/classes:./fuzion_generated_clazzes fzC_universe
```
leads to the following error:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "fzI_String.fzD_593_infix_plus(fzI_Any)" because the return value of "fzI_Any.fzD_7_as_string()" is null
	at fzC__L1456_io_INTERN___e_io_out__default_print_handler__1println.fzRoutine(Unknown Source)
	at fzC_io__1out__1println.fzRoutine(Unknown Source)
	at fzC_1say.fzRoutine(Unknown Source)
	at fzC_levels.fzRoutine(Unknown Source)
	at fzC_universe.main(Unknown Source)
```

**Comment by fridis** [comment]
These should be hard wired in the JVM backend and not modifyable, these intrinsics should go to Instrinsix.java and return constants that correspond to the code that was analysed by DFA.
