### ISSUE TITLE
be/jvm: VerifyError: Inconsistent stack height 1 != 0, with "complex" list and `Sequence.index []` (no arguments)

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#1974]
```
ones => 1 : ones
one => ones[]
say (one 10)
```
causes this error
```
error 1: java.lang.VerifyError: (class: fzC_list_i32__1nth, method: fzRoutine signature: (LfzI_Cons__i32__list_i32;I)LfzC_option_i32;) Inconsistent stack height 1 != 0
	at fzC_list_i32__1index__.fzRoutine(Unknown Source)
	at fzC_list_i32__index____INTERN_fun67__1call.fzRoutine(Unknown Source)
	at fzC_universe.fzRoutine(Unknown Source)
	at fzC_universe.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at dev.flang.be.jvm.Runner.runMain(Runner.java:120)
	at dev.flang.be.jvm.JVM$CompilePhase$4.finish(JVM.java:483)
	at dev.flang.be.jvm.JVM.lambda$createCode$0(JVM.java:674)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
	at dev.flang.be.jvm.JVM.createCode(JVM.java:665)
	at dev.flang.be.jvm.JVM.compile(JVM.java:650)
	at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:163)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:422)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:886)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:145)
	at dev.flang.util.Errors.runAndExit(Errors.java:762)
	at dev.flang.tools.Tool.run(Tool.java:145)
	at dev.flang.tools.Fuzion.main(Fuzion.java:535)


*** fatal errors encountered, stopping.
```

It is necessary that the sequence is reasonably "complex" (i.e. `[1, ..., 1].as_list` doesn't do the job), and it is necessary to use the `index []` (no arguments) feature (i.e. replacing the last two lines by `say (ones.take 10)` doesn't do the job either).

**Comment by michaellilltokiwa** [comment]
works now
