### ISSUE TITLE
be/jvm: `Clazz.fieldIndex()` did not find field, when DFA is off

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#1978]
```
$ cat ex2.fz
ex2 =>
  _ := 5

$ fz -jvm -Xdfa=off ex2.fz

error 1: java.lang.Error: Clazz.fieldIndex() did not find field ex2.#_0 in ex2
	at dev.flang.air.Clazz.fieldIndex(Clazz.java:2515)
	at dev.flang.fuir.FUIR.fieldIndex(FUIR.java:1734)
	at dev.flang.be.jvm.Names$1.rawName(Names.java:198)
	at dev.flang.be.jvm.Names$ClazzNames.get(Names.java:294)
	at dev.flang.be.jvm.Names.field(Names.java:542)
	at dev.flang.be.jvm.JVM$CompilePhase$2.compile(JVM.java:430)
	at dev.flang.be.jvm.JVM.lambda$createCode$0(JVM.java:672)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
	at dev.flang.be.jvm.JVM.createCode(JVM.java:665)
	at dev.flang.be.jvm.JVM.compile(JVM.java:650)
	at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:163)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:422)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:886)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:145)
	at dev.flang.util.Errors.runAndExit(Errors.java:762)
	at dev.flang.tools.Tool.run(Tool.java:145)
	at dev.flang.tools.Fuzion.main(Fuzion.java:535)


*** fatal errors encountered, stopping.

$ cat ex3.fz 
ex3 =>
  say "5"

$ fz -jvm -Xdfa=off ex3.fz 

error 1: java.lang.Error: Clazz.fieldIndex() did not find field (ref array u8).internal_array in ref array u8
	at dev.flang.air.Clazz.fieldIndex(Clazz.java:2515)
	at dev.flang.fuir.FUIR.fieldIndex(FUIR.java:1734)
	at dev.flang.be.jvm.Names$1.rawName(Names.java:198)
	at dev.flang.be.jvm.Names$ClazzNames.get(Names.java:294)
	at dev.flang.be.jvm.Names.field(Names.java:542)
	at dev.flang.be.jvm.JVM$CompilePhase$2.compile(JVM.java:430)
	at dev.flang.be.jvm.JVM.lambda$createCode$0(JVM.java:672)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
	at dev.flang.be.jvm.JVM.createCode(JVM.java:665)
	at dev.flang.be.jvm.JVM.compile(JVM.java:650)
	at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:163)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:422)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:886)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:145)
	at dev.flang.util.Errors.runAndExit(Errors.java:762)
	at dev.flang.tools.Tool.run(Tool.java:145)
	at dev.flang.tools.Fuzion.main(Fuzion.java:535)


*** fatal errors encountered, stopping.
```

Both examples work fine when using the C backend and DFA is off.

**Comment by michaellilltokiwa** [comment]
Backends do not work anymore without DFA, this is now intentional.
