### ISSUE TITLE
be/jvm: check-condition failure in `dev.flang.be.jvm.CodeGen:drop`

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#1981]
```
$ cat ex.fz 
ex is
  foo : choice unit i64 TRUE is
  bar list foo := nil

$ fz -jvm ex.fz

error 1: java.lang.Error: check-condition failed: dev.flang.be.jvm.CodeGen:drop:190
	at dev.flang.util.ANY.check(ANY.java:383)
	at dev.flang.be.jvm.CodeGen.drop(CodeGen.java:190)
	at dev.flang.be.jvm.CodeGen.drop(CodeGen.java:51)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:610)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:500)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:465)
	at dev.flang.be.jvm.JVM.codeForRoutine(JVM.java:919)
	at dev.flang.be.jvm.JVM.code(JVM.java:698)
	at dev.flang.be.jvm.JVM$CompilePhase$3.compile(JVM.java:447)
	at dev.flang.be.jvm.JVM.lambda$createCode$0(JVM.java:672)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
	at dev.flang.be.jvm.JVM.createCode(JVM.java:665)
	at dev.flang.be.jvm.JVM.compile(JVM.java:650)
	at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:163)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:422)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:886)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:145)
	at dev.flang.util.Errors.runAndExit(Errors.java:762)
	at dev.flang.tools.Tool.run(Tool.java:145)
	at dev.flang.tools.Fuzion.main(Fuzion.java:535)


*** fatal errors encountered, stopping.
```

**Comment by fridis** [comment]
Both solutions are fine, I do not have a clear preference. Maybe adding the choice type in Choices.tag is better to keep the special handing for nullable choices within Choice.java.

**Comment by fridis** [comment]
BTW, the type `foo` in the example is not needed: 
```
ex is
  bar list void := nil
```
suffices to reproduce this.
