### ISSUE TITLE
option<option<i32>> does not work

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#213]
This small example
```
 > cat testoption.fz
testoption is
  test <R>(x option<R>) => say x

  test<i32> nil
  test<i32> 42
  test<option<i32>> nil
  test<option<i32>> 42
```
causes a check to fail
```
 > CHECKS=true ./build/bin/fz testoption.fz 
--nil--
42

error 1: *** java.lang.Error: check-condition failed!
Call stack:


java.lang.Error: check-condition failed!
	at dev.flang.util.ANY.check(ANY.java:372)
	at dev.flang.air.Clazz.getChoiceTag(Clazz.java:1509)
	at dev.flang.be.interpreter.Interpreter.setChoiceField(Interpreter.java:973)
	at dev.flang.be.interpreter.Interpreter.tag(Interpreter.java:276)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:578)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:655)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:301)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:374)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:917)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:810)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:236)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:549)
	at dev.flang.tools.Tool.run(Tool.java:168)
	at dev.flang.tools.Fuzion.main(Fuzion.java:244)
```
without checks, assigning `nil` works, but printing `42` fails
```
 > ./build/bin/fz testoption.fz 
--nil--
42
--nil--

error 1: *** java.lang.IndexOutOfBoundsException: Index 42 out of bounds for length 2
Call stack:
option<i32>.prefix $: $FUZION/lib/Object.fz:32:27:
  prefix $ => Object.this.asString
--------------------------^
ref option<option<i32>>.asString: $FUZION/lib/option.fz:98:26:
    option.this ? v T => $v
-------------------------^
fuzion.std.out.print: $FUZION/lib/fuzion/std/out.fz:29:16:
    for c in s.asString.utf8 do
---------------^
io.ref defaultPrint.print: $FUZION/lib/io/out.fz:90:29:
  print(s Object) => stdout.print s
----------------------------^
io.ref defaultPrint.println: $FUZION/lib/io/out.fz:79:5:
    print s
----^
io.out.println: $FUZION/lib/io/out.fz:41:7:
    p.println s
------^
say: $FUZION/lib/say.fz:29:29:
say(s ref Object) => io.out.println s
----------------------------^
testoption.test<option<i32>>: /home/fridi/fuzion/work/testoption.fz:2:28:
  test <R>(x option<R>) => say x
---------------------------^
testoption: /home/fridi/fuzion/work/testoption.fz:7:3:
  test<option<i32>> 42
--^


java.lang.IndexOutOfBoundsException: Index 42 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at dev.flang.air.Clazz.getChoiceClazz(Clazz.java:1533)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:425)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:374)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:650)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:301)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:338)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:374)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:917)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:810)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:327)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:338)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:374)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:917)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:810)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:327)
```

**Comment by michaellilltokiwa** [comment]
I think using something like `option option i32` should never compile since the choice elements are not disjoint since we have `nil` twice?
