### ISSUE TITLE
require-condition in `calledFeature` in small example

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#2213]
```
ex =>
  mi : mutate is
  mi.go ()->
    ball is
    balls := (mutate.array ball).type.new mi 1 ball
```

**Comment by michaellilltokiwa** [comment]
```

error 1: java.lang.Error: require-condition1 failed: dev.flang.ast.Call:calledFeature:1068
        at dev.flang.util.ANY.require(ANY.java:78)
        at dev.flang.ast.Call.calledFeature(Call.java:1068)
        at dev.flang.ast.AbstractFeature.typeFeatureInherits(AbstractFeature.java:773)
        at dev.flang.ast.AbstractFeature.typeFeature(AbstractFeature.java:730)
        at dev.flang.ast.Call.lambda$resolveTypes$18(Call.java:2280)
        at dev.flang.util.List.map(List.java:451)
        at dev.flang.ast.AbstractType.applyToGenericsAndOuter(AbstractType.java:1385)
        at dev.flang.ast.Call.resolveTypes(Call.java:2273)
        at dev.flang.ast.DotType.resolveTypes(DotType.java:118)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1287)
        at dev.flang.ast.DotType.visit(DotType.java:100)
        at dev.flang.ast.Call.visit(Call.java:1154)
        at dev.flang.ast.Feature.visit(Feature.java:1932)
        at dev.flang.ast.Block.visit(Block.java:228)
        at dev.flang.ast.Block.visit(Block.java:41)
        at dev.flang.ast.Impl.visit(Impl.java:314)
        at dev.flang.ast.Feature.visit(Feature.java:1047)
        at dev.flang.ast.Feature.internalResolveTypes(Feature.java:1336)
        at dev.flang.ast.Resolution.resolveTypes(Resolution.java:482)
        at dev.flang.ast.Function.propagateExpectedType2(Function.java:302)
        at dev.flang.ast.Call.inferGenericLambdaResult(Call.java:2052)
        at dev.flang.ast.Call.inferGenericsFromArgs(Call.java:1816)
        at dev.flang.ast.Call.inferGenericsFromArgs(Call.java:1704)
        at dev.flang.ast.Call.resolveTypes(Call.java:2220)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1286)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1278)
        at dev.flang.ast.Call.visit(Call.java:1157)
        at dev.flang.ast.Block.visit(Block.java:228)
        at dev.flang.ast.Block.visit(Block.java:41)
        at dev.flang.ast.Impl.visit(Impl.java:314)
        at dev.flang.ast.Feature.visit(Feature.java:1047)
        at dev.flang.ast.Feature.internalResolveTypes(Feature.java:1336)
        at dev.flang.ast.Resolution.resolveOne(Resolution.java:391)
        at dev.flang.ast.Resolution.resolve(Resolution.java:358)
        at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:265)
        at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:184)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:906)
        at dev.flang.tools.Tool.lambda$run$0(Tool.java:145)
        at dev.flang.util.Errors.runAndExit(Errors.java:790)
        at dev.flang.tools.Tool.run(Tool.java:145)
        at dev.flang.tools.Fuzion.main(Fuzion.java:557)

```
