### ISSUE TITLE
JVM: "no targets for access of" when using `set_exit_code`

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2224]
This occurs in the JVM backend:  
```
 > echo "_ := set_exit_code 1" | ./build/bin/fz -

error 1: java.lang.VerifyError: (class: fzC_1set_exit_code, method: fzRoutine signature: (I)LfzC_outcome_unit;) Unable to pop operand off an empty stack
	at fzC_universe.fzRoutine(Unknown Source)
	at fzC_universe.fz_run(Unknown Source)
	at dev.flang.be.jvm.runtime.FuzionThread.lambda$new$1(FuzionThread.java:90)
	at dev.flang.util.Errors.runAndExit(Errors.java:790)
	at dev.flang.be.jvm.runtime.FuzionThread.lambda$new$2(FuzionThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)


*** fatal errors encountered, stopping.
```
Similar and probably related is this case:
```
 > echo "_ := x; x outcome unit =>" | ./build/bin/fz -

error 1: java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:101)
	at java.base/java.util.Stack.pop(Stack.java:83)
	at dev.flang.fuir.analysis.AbstractInterpreter.pop(AbstractInterpreter.java:380)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:619)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1087)
```

**Comment by michaellilltokiwa** [comment]
new error now, 2nd example works without error now:
```
error 1: no targets for access of Exit_Handler.set_exit_code within exit.set_exit_code
Call stack:
3exit__1set_exit_code
1set_exit_code
universe

*** fatal errors encountered, stopping.
```

**Comment by michaellilltokiwa** [comment]
Problem is mitigated by using this diff which comments out the precondition of an abstract feature in the _interface_ `ExitHandler`:
```patch
diff --git a/lib/exit.fz b/lib/exit.fz
index d171998ba..37194b539 100644
--- a/lib/exit.fz
+++ b/lib/exit.fz
@@ -148,6 +148,6 @@ public Exit_Handler ref is
   # set the stored exit code, which, by default, is zero
   #
   public set_exit_code(code i32) outcome unit
-    pre
-      0 ≤ code ≤ 127
+    # pre
+    #   0 ≤ code ≤ 127
     => abstract
```
