### ISSUE TITLE
Returning Tuple from a loop causes crash 

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#228]
The following small example apparently results in `u` not being initialized
```
> cat testTupleFromLoop.fz 
testTupleFromLoop is

  s =>
    (_,u) := for
      x := (1, "q")
      n in 1..1
    while false else
      x
    $u

  _ := s
```
this crashes the interpreter
```
 > ./build/bin/fz testTupleFromLoop.fz 

error 1: *** java.lang.NullPointerException: Cannot invoke "dev.flang.be.interpreter.ValueWithClazz.clazz()" because "<local21>" is null
Call stack:
testTupleFromLoop.s: /home/fridi/fuzion/work/testTupleFromLoop.fz:9:5:
    $u
----^
testTupleFromLoop: /home/fridi/fuzion/work/testTupleFromLoop.fz:11:8:
  _ := s
-------^


java.lang.NullPointerException: Cannot invoke "dev.flang.be.interpreter.ValueWithClazz.clazz()" because "<local21>" is null
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:324)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:374)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:338)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:374)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:917)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:810)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:327)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:338)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:374)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:374)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:917)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:810)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:236)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:558)
	at dev.flang.tools.Tool.run(Tool.java:168)
	at dev.flang.tools.Fuzion.main(Fuzion.java:253)
```
and segfaults in compiled code
```
 > ./build/bin/fz -c testTupleFromLoop.fz  && ./testTupleFromLoop
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

**Comment by michaellilltokiwa** [comment]
does not work in c backend even for none tuples:
```
issue228 is

  s =>
    u := for
      x := 1
      n in 1..1
    while false else
      x
    u

  _ := s
```
```
error 1: reading uninitialized field issue228.s.#loop0.x from instance of issue228.s.#loop0
fields available:
  268438796:issue228.s.#loop0.x,
  268438797:issue228.s.#loop0.n,
  268438806:issue228.s.#loop0.#^issue228.s.#loop0

NYI: HACK: Using value version instead: null
one error.
```

**Comment by michaellilltokiwa** [comment]
Changed label to frontend because I assume the bug is in the generated code for the loop. (Loop.java)

**Comment by michaellilltokiwa** [comment]
now fixed
