### ISSUE TITLE
Small example with inferred argument types fails to infer the argument types in time

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2290]
In this example
```
f(d) => (12 >= d.r)
_ := [1].filter x->(f 42)
```
We would expect an error that `i32` does not have an inner feature `r`, but we get this confusing message
```
 > $FUZION/bin/fz dec2_no_targets.fz

dec2_no_targets.fz:1:18: error 1: NYI: in f no targets for Call to id void target UNIT
f(d) => (12 >= d.r)
-----------------^

one error.
```
apparently, `f` is resolved before the call to `f` was.
```

**Comment by fridis** [comment]
With a small modification, this can crash the DFA:
```
c(a) => a
_ := [1].filter x->(c 1)
```
results in
```
 > ./build//bin/fz test.fz

error 1: java.lang.Error: DFA encountered Unexpected value in match: class dev.flang.fuir.analysis.dfa.NumericValue 'i32:1'  for match of type bool
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$match$3(DFA.java:548)
	at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:352)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.match(DFA.java:532)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.match(DFA.java:83)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:690)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1087)
	at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:2042)
	at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:2004)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:391)

```
