### ISSUE TITLE
recursion results in `EmptyStackException`

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2306]
this 
```
ping => if true then ping; true
_ := ping
```
causes
```
 > ./build/bin/fz ~/fuzion/work/empty_stack.fz

error 1: java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:101)
	at java.base/java.util.Stack.pop(Stack.java:83)
	at dev.flang.fuir.analysis.AbstractInterpreter.pop(AbstractInterpreter.java:380)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:619)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
	at dev.flang.be.jvm.JVM.codeForRoutine(JVM.java:1120)
	at dev.flang.be.jvm.JVM.code(JVM.java:837)
	at dev.flang.be.jvm.JVM$CompilePhase$3.compile(JVM.java:459)
	at dev.flang.be.jvm.JVM.lambda$createCode$0(JVM.java:811)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
	at dev.flang.be.jvm.JVM.createCode(JVM.java:804)
	at dev.flang.be.jvm.JVM.compile(JVM.java:789)
	at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:163)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:444)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:908)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:145)
	at dev.flang.util.Errors.runAndExit(Errors.java:790)
	at dev.flang.tools.Tool.run(Tool.java:145)
	at dev.flang.tools.Fuzion.main(Fuzion.java:557)


*** fatal errors encountered, stopping.

```

**Comment by michaellilltokiwa** [comment]
meanwhile fixed:
```
error 1: java.lang.StackOverflowError
        at fzC_ping.fzRoutine(Unknown Source)
        at fzC_ping.fzRoutine(Unknown Source)
        at fzC_ping.fzRoutine(Unknown Source)
....
```
