### ISSUE TITLE
be/c:  ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#238]
this example: 
```Fuzion
ex =>

  say ([0,1,2,3,4]
    .groupBy<string>((x) -> if x % 2 == 0 then "even" else "uneven")
    .items.mapSequence<string>((kv) -> (k,v):=kv; "$k => $v")
    .fold (strings.concat "\n"))
```
on his branch: https://github.com/michaellilltokiwa/fuzion/tree/lib/Sequence__group_by
leads to:
```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at dev.flang.be.c.C.createCode(C.java:655)
        at dev.flang.be.c.C.createCode(C.java:342)
        at dev.flang.be.c.C.codeForRoutine(C.java:1118)
        at dev.flang.be.c.C.code(C.java:1062)
        at dev.flang.be.c.C$CompilePhase$4.compile(C.java:67)
        at dev.flang.be.c.C.lambda$createCode$3(C.java:237)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
        at dev.flang.be.c.C.createCode(C.java:233)
        at dev.flang.be.c.C.compile(C.java:159)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:560)
        at dev.flang.tools.Tool.run(Tool.java:168)
        at dev.flang.tools.Fuzion.main(Fuzion.java:253)
```

**Comment by fridis** [comment]
This is related to #304, a match case does not match anything since the types differ in their outer being ref or non-ref.
