### ISSUE TITLE
AoC issue: Interpreter crash with index-out-of-bounds

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2383]
This code
```
dec16_part1 is

  input := [ ".|...\\....",
             "|.-.\\.....",
             ".....|-...",
             "........|.",
             "..........",
             ".........\\",
             "..../.\\\\..",
             ".-.-/..|..",
             ".|....-|.\\",
             "..//.|...."].map (.as_codepoints)
  area := array2 String input.count input[0].count i,j->input[i][j]

  part1 =>
    lm : mutate.
    lm.go ()->
      visited := (lm.array i32).type.new lm area.length 0
      r => 1
      l => 2
      u => 4
      d => 8
      ix(x,y) => y+x*area.length1
      trace(x,y,w i32) =>
        if ((x ∈ area.indices1) &&
            (y ∈ area.indices0) &&
            (visited[ix x y] & d) = 0) then
          visited[ix x y] := visited[ix x y] | d
          c := area[y,x]
          if  w = r  &&  c = "."              then trace x+1 y   w
          if  w = l  &&  c = "."              then trace x-1 y   w
          if  w = u  &&  c = "."              then trace x   y-1 w
          if  w = d  &&  c = "."              then trace x   y+1 w
          if  w = r  &&  c = "-"              then trace x+1 y   w
          if  w = l  &&  c = "-"              then trace x-1 y   w
          if  w = u  &&  c = "|"              then trace x   y-1 w
          if  w = d  &&  c = "|"              then trace x   y+1 w
          if (w = r) && (c = "/"  || c = "|") then trace x   y-1 u
          if (w = r) && (c = "\\" || c = "|") then trace x   y+1 d
          if (w = l) && (c = "/"  || c = "|") then trace x   y-1 d
          if (w = l) && (c = "\\" || c = "|") then trace x   y+1 u
          if (w = u) && (c = "/"  || c = "-") then trace x-1 y   l
          if (w = u) && (c = "\\" || c = "-") then trace x+1 y   r
          if (w = d) && (c = "/"  || c = "-") then trace x-1 y   l
          if (w = d) && (c = "\\" || c = "-") then trace x+1 y   r
      trace 0 0 r
      (visited.filter !=0).count

  say "part1 $part1"
```
causes this crash in the interpreter
```
 > ~/fuzion/clean/fuzion/build/bin/fz -interpreter part1_interpreter_crash_on_test_input.fz 

error 1: *** java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
Call stack:
dec16_part1.part1.#fun1.call.trace: /home/fridi/fuzion/advent_of_code/fuzion_aoc/2023/16/part1_interpreter_crash_on_test_input.fz:38:52:
          if (w = r) && (c = "/"  || c = "|") then trace x   y-1 u
---------------------------------------------------^^^^^
dec16_part1.part1.#fun1.call.trace: /home/fridi/fuzion/advent_of_code/fuzion_aoc/2023/16/part1_interpreter_crash_on_test_input.fz:30:52:
          if  w = r  &&  c = "."              then trace x+1 y   w
---------------------------------------------------^^^^^
dec16_part1.part1.#fun1.call: /home/fridi/fuzion/advent_of_code/fuzion_aoc/2023/16/part1_interpreter_crash_on_test_input.fz:46:7:
      trace 0 0 r
------^^^^^
(dec16_part1.part1.lm.go i32).fo.#fun57.call: $FUZION/lib/effect.fz:167:30:
    fo () -> option T is ()->f()
-----------------------------^
(dec16_part1.part1.lm.go i32).#fun2.call: $FUZION/lib/effect.fz:168:14:
    r := run fo _->nil
-------------^
(dec16_part1.part1.lm.run (option i32)).#fun0.call: $FUZION/lib/effect.fz:73:23:
    cf := Effect_Call f
----------------------^
(Effect_Call (option i32)).call: $FUZION/lib/effect.fz:115:16:
    set res := f()
---------------^
dec16_part1.part1.lm.run (option i32): $FUZION/lib/effect.fz:74:5:
    abortable cf
----^
dec16_part1.part1.lm.go i32: $FUZION/lib/effect.fz:168:10:
    r := run fo _->nil
---------^
dec16_part1.part1: /home/fridi/fuzion/advent_of_code/fuzion_aoc/2023/16/part1_interpreter_crash_on_test_input.fz:17:8:
    lm.go ()->
-------^^
dec16_part1: /home/fridi/fuzion/advent_of_code/fuzion_aoc/2023/16/part1_interpreter_crash_on_test_input.fz:49:15:
  say "part1 $part1"
--------------^^^^^



error 2: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at dev.flang.be.interpreter.Instance.storeNonRef(Instance.java:402)
	at dev.flang.be.interpreter.Instance.storeNonRef(Instance.java:382)
	at dev.flang.be.interpreter.Interpreter.setNonRefField(Interpreter.java:1181)
	at dev.flang.be.interpreter.Interpreter.setFieldSlot(Interpre
```

**Comment by michaellilltokiwa** [comment]
now effectively duplicate of #2381 because new interpreter
