### ISSUE TITLE
`$"{3}".dynamic_type` causes crash

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2402]
This
```
_ :=  $"{3}".dynamic_type
```
results in
```
 > ~/fuzion/clean/fuzion/build/bin/fz test_str.fz 

error 1: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at dev.flang.air.Clazz.typeName(Clazz.java:2077)
	at dev.flang.fuir.FUIR.clazzTypeName(FUIR.java:516)
	at dev.flang.fuir.analysis.dfa.DFA.lambda$static$2(DFA.java:1313)
	at dev.flang.fuir.analysis.dfa.Call.result(Call.java:207)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:392)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:337)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$1(DFA.java:298)
	at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:352)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:290)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:256)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:83)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:654)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1160)
	at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:2036)
	at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:1998)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:391)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:337)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$1(DFA.java:298)
	at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:352)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:290)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:256)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:83)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:654)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1160)
	at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:2036)
	at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:1998)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:391)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:337)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$1(DFA.java:298)
	at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:352)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:290)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:256)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:83)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:654)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1160)
	at dev.flang.fuir.analysis.dfa.DFA.iteration(DFA.java:1125)
	at dev.flang.fuir.analysis.dfa.DFA.findFixPoint(DFA.java:1088)
	at dev.flang.fuir.analysis.dfa.DFA.dfa(DFA.java:1070)
	at dev.flang.fuir.analysis.dfa.DFA.new_fuir(DFA.java:922)
	at dev.flang.be.jvm.JVM.<init>(JVM.java:762)
	at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:163)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:444)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:908)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:145)
	at dev.flang.util.Errors.runAndExit(Errors.java:790)
	at dev.flang.tools.Tool.run(Tool.java:145)
	at dev.flang.tools.Fuzion.main(Fuzion.java:557)


*** fatal errors encountered, stopping.
```
and this
```
_ :=  "{3}".dynamic_type
```
results in 
```
 > ~/fuzion/clean/fuzion/build/bin/fz test_str1.fz 

error 1: java.lang.VerifyError: (class: fzC__L4187_Types__get___concatINTERN_2_INTERN_anonymous5INTERN_0, method: fzRoutine signature: ()LfzI_Type;) Unable to pop operand off an empty stack
	at fzC__L479_String_INT____2concat__INTERN_anonymous5__dynamic_type.fzRoutine(Unknown Source)
	at fzC_universe.fzRoutine(Unknown Source)
	at fzC_universe.fz_run(Unknown Source)
	at dev.flang.be.jvm.runtime.FuzionThread.lambda$new$1(FuzionThread.java:90)
	at dev.flang.util.Errors.runAndExit(Errors.java:790)
	at dev.flang.be.jvm.runtime.FuzionThread.lambda$new$2(FuzionThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)


*** fatal errors encountered, stopping.

```

**Comment by michaellilltokiwa** [comment]
```
_ := ("" + 3.as_string).dynamic_type.as_string
```

This generates code to call `Type.name` directly. Not sure why though.

**Comment by michaellilltokiwa** [comment]
same problem
```
ex is

  type.a String =>
    ref: String
      utf8 Sequence u8 => []

  say ex.a.dynamic_type.as_string
```
