### ISSUE TITLE
check condition failure in Call.propagateExpectedType()

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#256]
This (broken) example:
```
example =>
  for i in (i64.max -500000000000)..i64.max do
```
yields:
```
java.lang.Error: check-condition2 failed!
        at dev.flang.util.ANY.check(ANY.java:390)
        at dev.flang.ast.Call.propagateExpectedType(Call.java:1625)
        at dev.flang.ast.Feature$5.action(Feature.java:1618)
        at dev.flang.ast.Feature$5.action(Feature.java:1616)
        at dev.flang.ast.Call.visit(Call.java:954)
        at dev.flang.ast.Call.visit(Call.java:951)
        at dev.flang.ast.Call.visit(Call.java:951)
        at dev.flang.ast.AbstractAssign.visit(AbstractAssign.java:122)
        at dev.flang.ast.Feature$9.visit(Feature.java:1883)
        at dev.flang.ast.Feature$9.visit(Feature.java:1861)
...
```

**Comment by fridis** [comment]
This smaller example has the same effect
```
ex256 =>
  i8.max 1
```
Problem is that `i8.max` is called with one argument, which does not exist. Some check does not handle this well.
