### ISSUE TITLE
require-condition when calling `Type.name`

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#2577]
```
ex =>
  say Type.name
```
```
error 1: java.lang.Error: require-condition1 failed: dev.flang.air.Clazz:typeName:2086
        at dev.flang.util.ANY.require(ANY.java:84)
        at dev.flang.air.Clazz.typeName(Clazz.java:2086)
        at dev.flang.fuir.FUIR.clazzTypeName(FUIR.java:516)
        at dev.flang.fuir.analysis.dfa.DFA.lambda$static$3(DFA.java:1343)
        at dev.flang.fuir.analysis.dfa.DFA.lambda$put$0(DFA.java:773)
        at dev.flang.fuir.analysis.dfa.Call.result(Call.java:216)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:394)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:338)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$1(DFA.java:299)
        at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:364)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:291)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:257)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:84)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:664)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:525)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:488)
        at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1190)
        at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:2192)
        at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:2154)
        at dev.flang.fuir.analysis.dfa.DFA.dfa(DFA.java:1089)
        at dev.flang.fuir.analysis.dfa.DFA.new_fuir(DFA.java:941)
        at dev.flang.be.c.C.<init>(C.java:644)
        at dev.flang.tools.Fuzion$Backend$2.process(Fuzion.java:141)
        at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:456)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:920)
        at dev.flang.tools.Tool.lambda$run$0(Tool.java:140)
        at dev.flang.util.Errors.runAndExit(Errors.java:878)
        at dev.flang.tools.Tool.run(Tool.java:140)
        at dev.flang.tools.Fuzion.main(Fuzion.java:569)

```

**Comment by michaellilltokiwa** [comment]
> do you really think this is a bug?
> 
> the `Type` feature isn't a type feature, and the intrinsic is intended to be only called on type features.

Not sure, in any way it should fail more gracefully.
