### ISSUE TITLE
internal errors and failed type inference on single-line `fib` example

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2715]
Maybe this needs to be split up in three issues: 

Tried to implement the fibonaccie example from [this paper](https://dl.acm.org/doi/pdf/10.1145/3607853) in Fuzion but ran into this
```
 > ./build/bin/fz -e "fibs => { [ 0, 1 ] ++ fibs.zip (fibs.drop 1) (+)}; say fibs"

error 1: no targets for access of fibs within fibs
Call stack:
fibs
universe

*** fatal errors encountered, stopping.
```
and this
```
 > ./build/bin/fz -e "fibs Sequence i32 => { 0 : (1 : fibs.zip (fibs.drop 1) (+))}; say fibs"

command line:1:57: error 1: NYI: in fibs.#fun1.call.#fun2.call no targets for Call fibs.#fun0(outer fibs) fibs.#fun0 target fibs.#fun1.call.#fun2.call
fibs Sequence i32 => { 0 : (1 : fibs.zip (fibs.drop 1) (+))}; say fibs
--------------------------------------------------------^

one error.
```
and finally this
```
 > ./build/bin/fz -e "fibs => { 0 : (1 : fibs.zip (fibs.drop 1) (+))}; say fibs"

command line:1:20: error 1: Failed to infer type of expression.
fibs => { 0 : (1 : fibs.zip (fibs.drop 1) (+))}; say fibs
-------------------^^^^
Expression with unknown type: 'fibs'

one error.

```

**Comment by michaellilltokiwa** [comment]
first two are solved, with last:
```
error 1: java.lang.Error: check-condition failed: Call.java:2594 "(Errors.any());"
        at dev.flang.util.ANY.check(ANY.java:440)
        at dev.flang.ast.Call.resolveTypes(Call.java:2594)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1385)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1375)
        at dev.flang.ast.Call.visit(Call.java:1207)
...
```
