### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#2740]
```
ex =>
  Java.java.nio.file.Path.__k__of "not a valid file" []
```
```
error 1: java.lang.IllegalArgumentException: argument type mismatch
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:107)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at dev.flang.be.jvm.runtime.Runtime.lambda$invoke$1(Runtime.java:982)
        at dev.flang.be.jvm.runtime.Runtime.invokeAndWrapException(Runtime.java:953)
        at dev.flang.be.jvm.runtime.Runtime.invoke(Runtime.java:982)
        at dev.flang.be.jvm.runtime.Runtime.fuzion_java_call_s0(Runtime.java:1021)
        at fzC_fuzion__java__4call_static_Java_java_nio_file_Path.fzRoutine(Unknown Source)
        at fzC__L11295_Java__java__ring_s__u00005b_Ljava_7_lang_7_String_s_.fzRoutine(Unknown Source)
        at fzC_Java__java__nio__file__Path_static__2_u_k__of.fzRoutine(Unknown Source)
        at fzC_ex.fzRoutine(Unknown Source)
        at fzC_universe.fz_run(Unknown Source)
        at dev.flang.be.jvm.runtime.FuzionThread.lambda$new$1(FuzionThread.java:97)
        at dev.flang.util.Errors.runAndExit(Errors.java:878)
        at dev.flang.be.jvm.runtime.FuzionThread.lambda$new$2(FuzionThread.java:106)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by michaellilltokiwa** [comment]
@maxteufel probably related to the arraystoreexception, what do you think?

**Comment by michaellilltokiwa** [comment]
It is passing down an array of Java.java.lang.__jString but intrinsic expect array of java-Strings.
```
  public __k__of_Ljava_7_lang_7_String_s__u00005b_Ljava_7_lang_7_String_s_(arg0 String, arg1 Sequence (Java.java.lang.__jString)) Java.java.nio.file.Path =>
    match fuzion.java.call_static (Java.java.nio.file.Path) "java.nio.file.Path" "of" "(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path;" [(fuzion.java.string_to_java_object Java.java.nio.file.Path_static.__k__of_Ljava_7_lang_7_String_s__u00005b_Ljava_7_lang_7_String_s_.this.arg0); (fuzion.java.array_to_java_object (Java.java.lang.__jString) Java.java.nio.file.Path_static.__k__of_Ljava_7_lang_7_String_s__u00005b_Ljava_7_lang_7_String_s_.this.arg1)]
      e error => panic e.msg
      r Java.java.nio.file.Path => r
```

**Comment by michaellilltokiwa** [comment]
meanwhile fixed
