### ISSUE TITLE
require-condition failure in AbstractFeature.handDown()

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#281]
this example:

```
ex =>
  reducing_fn<RR, TT> ref : Function<RR,RR,TT> is
    redef call(res RR, val TT) RR is abstract

  a := ref : reducing_fn<i32,i32>
    redef call(x,y i32) i32 is
      0

  say a
```

yields:
```
java.lang.Error: require-condition1 failed!
        at dev.flang.util.ANY.require(ANY.java:82)
        at dev.flang.ast.AbstractFeature.handDown(AbstractFeature.java:794)
        at dev.flang.air.Clazz.findRedefinition(Clazz.java:922)
        at dev.flang.air.Clazz.lookup(Clazz.java:1020)
        at dev.flang.air.Clazz.lookup(Clazz.java:957)
        at dev.flang.air.Clazz.lookupIfInstantiated(Clazz.java:899)
        at dev.flang.air.Clazz.lambda$findAllClasses$0(Clazz.java:1303)
        at dev.flang.air.Clazzes.calledDynamically(Clazzes.java:523)
        at dev.flang.air.Clazzes.findClazzes(Clazzes.java:831)
        at dev.flang.air.Clazz$1.action(Clazz.java:1287)
        at dev.flang.ast.Stmnt.visitStatements(Stmnt.java:72)
        at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:123)
        at dev.flang.ast.Box.visitStatements(Box.java:156)
        at dev.flang.ast.AbstractAssign.visitStatements(AbstractAssign.java:140)
        at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
        at dev.flang.ast.AbstractCase.visitStatements(AbstractCase.java:152)
        at dev.flang.ast.AbstractMatch.visitStatements(AbstractMatch.java:128)
        at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
        at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:121)
        at dev.flang.ast.Box.visitStatements(Box.java:156)
        at dev.flang.ast.AbstractAssign.visitStatements(AbstractAssign.java:140)
        at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
        at dev.flang.ast.AbstractFeature.visitStatements(AbstractFeature.java:1041)
        at dev.flang.air.Clazz.inspectCode(Clazz.java:1237)
        at dev.flang.air.Clazz.findAllClasses(Clazz.java:1281)
        at dev.flang.air.Clazzes.findAllClasses(Clazzes.java:421)
        at dev.flang.fuir.FUIR.<init>(FUIR.java:159)
        at dev.flang.opt.Optimizer.fuir(Optimizer.java:73)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:549)
        at dev.flang.tools.Tool.run(Tool.java:168)
        at dev.flang.tools.Fuzion.main(Fuzion.java:253)
```

**Comment by fridis** [comment]
This was fixed with c02bdfc1850b88144f6b3cfa3ba6f52ac258c971
