### ISSUE TITLE
inheritance of type features does not support type parameters

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#284]
When inherting features as in 
```
  a(T1 type, T2 type) is
  b : a i32 f64 is
```
Currently. the corresponding type feature `b.type` inherits from `a.type`, but not from `(a i32 f64).type` since `a.type` is not generic. Need to find Fuzion example code where this would be relevant and then fix (or ignore) this.

**Comment by fridis** [comment]
Type features now have type parameters corresponding to the underlying original features. So the following example should work, but does crash:
```
a(T1 type, T2 type) is
  type.af => say "in a.type: $T1 $T2"
  
b : a i32 f64 is
  say T1
  say T2
  type.bf => af; say "in b.type:"

b.type.bf
_ := b
```
currently results in 
```
 > ./build/bin/fz ex_284.fz 

error 1: java.lang.Error: NYI: cannot find actual generic for 'a.T1' in heir outer clazz 'b'.
	at dev.flang.air.Clazz.typeParameterActualType(Clazz.java:2017)
	at dev.flang.air.Clazz.determineResultClazz(Clazz.java:2102)
	at dev.flang.air.Clazz.dependencies(Clazz.java:415)
	at dev.flang.air.Clazzes.create(Clazzes.java:389)
	at dev.flang.air.Clazzes.clazzWithSpecificOuter(Clazzes.java:1226)
	at dev.flang.air.Clazz.lookup(Clazz.java:1160)
	at dev.flang.air.Clazzes.findClazzes(Clazzes.java:888)
	at dev.flang.air.Clazz$1.action(Clazz.java:1428)
	at dev.flang.ast.Stmnt.visitStatements(Stmnt.java:65)
	at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:112)
	at dev.flang.ast.Box.visitStatements(Box.java:157)
	at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:106)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractFeature.visitStatements(AbstractFeature.java:1456)
	at dev.flang.air.Clazz.inspectCode(Clazz.java:1378)
	at dev.flang.air.Clazz.findAllClasses(Clazz.java:1422)
	at dev.flang.air.Clazzes.findAllClasses(Clazzes.java:456)
	at dev.flang.fuir.FUIR.<init>(FUIR.java:198)
	at dev.flang.opt.Optimizer.fuir(Optimizer.java:73)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:367)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:832)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:704)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)


*** fatal errors encountered, stopping.
```

**Comment by fridis** [comment]
This works no: 
```
 > cat ex_284.fz 
a(T1 type, T2 type) is
  type.af => say "in a.type: $T1 $T2"

b : a i32 f64 is
  say T1
  say T2
  type.bf => af; say "in b.type:"

b.type.bf
_ := b
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz ex_284.fz 
in a.type: Type of 'i32' Type of 'f64'
in b.type:
Type of 'i32'
Type of 'f64'
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c -o=ex_284 ex_284.fz && ./ex_284
in a.type: Type of 'i32' Type of 'f64'
in b.type:
Type of 'i32'
Type of 'f64'
 > 
```
