### ISSUE TITLE
IndexOutOfBoundsException: Index -1,  in FUIR.boxValueClazz box._valAndRefClazzId is -1

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#294]
This example fails in c-backend, when `call ... is abstract` in `reducing_fn` is commented out.
Note: Preconditions currently need to be turned off to reproduce error, because of another possibly related? bug,
```
ex is

  ages := map (Sequence i32) u64 i32 (x -> x.as_i32)
  say (into i32 u64 [(u64 4), (u64 12), (u64 30)] ages)

  into(TAcc,T type, seq Sequence<T>, xf transducer(Sequence(TAcc),TAcc,T)) Sequence(TAcc) is
    rf := ref : reducing_fn((Sequence TAcc),TAcc)
      call(res Sequence(TAcc), val TAcc) Sequence(TAcc) is
        res ++ [val]
    red := xf.call rf
    for
      res := Sequences.empty(TAcc) , red.call res el
      el in seq do
    else
      res

  # a transducer mappping values from T to U
  map(TAcc,T,U type, mapper T -> U) transducer(TAcc,U,T) is
    ref : transducer(TAcc,U,T)
      call(red reducing_fn(TAcc,U)) =>
        ref : reducing_fn(TAcc,T)
          call(res TAcc, val T) =>
            red.call res (mapper val)


  # a reducing function takes a previous result and a value and returns a new result
  reducing_fn(TAcc,T type) ref : Function<TAcc,TAcc,T> is

    # NYI redef call abstract is currently necessary because of bug in c backend
    # call(res TAcc, val T) TAcc is abstract

  # TAcc result     type
  # B    input      type
  # C    transduced type
  transducer(TAcc,B,C type) ref : Function(reducing_fn(TAcc,C), reducing_fn(TAcc,B)) is

    # NYI redef call abstract is currently necessary because of bug in c backend
    call(rf reducing_fn(TAcc,B)) reducing_fn(TAcc,C) is abstract
```
```
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 453
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at dev.flang.air.Clazz.getRuntimeData(Clazz.java:1348)
        at dev.flang.fuir.FUIR.boxValueClazz(FUIR.java:1096)
        at dev.flang.be.c.C.createCode(C.java:516)
        at dev.flang.be.c.C.createCode(C.java:343)
        at dev.flang.be.c.C.codeForRoutine(C.java:1124)
        at dev.flang.be.c.C.code(C.java:1072)
        at dev.flang.be.c.C$CompilePhase$4.compile(C.java:67)
        at dev.flang.be.c.C.lambda$createCode$3(C.java:238)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
        at dev.flang.be.c.C.createCode(C.java:234)
        at dev.flang.be.c.C.compile(C.java:159)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:560)
        at dev.flang.tools.Tool.run(Tool.java:168)
        at dev.flang.tools.Fuzion.main(Fuzion.java:253)
```

**Comment by fridis** [comment]
works now: 
```
 > ./build/bin/fz -c ex294.fz
 > ./ex
[4,12,30]
```
