### ISSUE TITLE
Issue with redefined asString of parent class: ArrayIndexOutOfBoundsException, fatal errors encountered

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#298]
This fails in both backends:
```
ex is
  a := CTrie<i32,i32>
  a.add 1 2
  say a
```
explicitly calling `asString` on a makes it work:
```
ex is
  a := CTrie<i32,i32>
  a.add 1 2
  say a.asString
```
failures:
```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at dev.flang.be.c.C.createCode(C.java:654)
        at dev.flang.be.c.C.createCode(C.java:343)
        at dev.flang.be.c.C.codeForRoutine(C.java:1124)
        at dev.flang.be.c.C.code(C.java:1072)
        at dev.flang.be.c.C$CompilePhase$4.compile(C.java:67)
        at dev.flang.be.c.C.lambda$createCode$3(C.java:238)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
        at dev.flang.be.c.C.createCode(C.java:234)
        at dev.flang.be.c.C.compile(C.java:159)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:560)
        at dev.flang.tools.Tool.run(Tool.java:168)
        at dev.flang.tools.Fuzion.main(Fuzion.java:253)
```
```

$FUZION/lib/ctrie.fz:250:5: error 1: no match found
    match i.main
----^
For value of clazz: CTrie<i32, i32>.CNode
Permitted clazzes: ref CTrie<i32, i32>.CNode, CTrie<i32, i32>.TNode, list<CTrie<i32, i32>.SNode>
Call stack:
ref CTrie<i32, i32>.lookup: $FUZION/lib/ctrie.fz:239:12:
    res := ilookup r k 0 nil
-----------^
ref CTrie<i32, i32>.index [ ]: $FUZION/lib/ctrie.fz:379:5:
    lookup k
----^
ref CTrie<i32, i32>.asString.@31197: $FUZION/lib/map.fz:70:33:
      r := "", r + c + "($k => {index[] k})"
--------------------------------^
ref CTrie<i32, i32>.asString: $FUZION/lib/map.fz:69:5:
    for
----^
fuzion.std.out.print: $FUZION/lib/fuzion/std/out.fz:31:16:
    for c in s.asString.utf8 do
---------------^
io.ref defaultPrintToOut.print: $FUZION/lib/io/out.fz:60:29:
  print(s Object) => stdout.print s
----------------------------^
io.ref defaultPrintToOut.println: $FUZION/lib/io/printEffect.fz:60:5:
    print s
----^
io.out.println: $FUZION/lib/io/printEffect.fz:41:7:
    p.println s
------^
say: $FUZION/lib/say.fz:31:29:
say(s ref Object) => io.out.println s
----------------------------^
ex: /home/sam/playground/test.fz:5:3:
  say a
--^

*** fatal errors encountered, stopping.
```

**Comment by michaellilltokiwa** [comment]
meanwhile fixed. closing
