### ISSUE TITLE
multiple inheritance may result in crash

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#3027]
This small example inherits and redefines two features `f` with incompatible result types
```
a         is        f => 42
B ref     is        f => "B.f"
aB : a, B is  redef f => 4711

b B := aB
say b.f
```
which should produce an error but it results in a crash
```
 > ./build/bin/fz test_conflicting_inheritance.fz

error 1: java.lang.IndexOutOfBoundsException: Index -805306369 out of bounds for length 12
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at dev.flang.ir.IR.getExpr(IR.java:179)
	at dev.flang.fuir.FUIR.sitePos(FUIR.java:2274)
	at dev.flang.fuir.analysis.dfa.Instance.readFieldFromInstance(Instance.java:215)
	at dev.flang.fuir.analysis.dfa.Value.readField(Value.java:260)
	at dev.flang.fuir.analysis.dfa.Call.result(Call.java:302)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:392)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:339)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$0(DFA.java:293)
	at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:388)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:285)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:255)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:90)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:651)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:524)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:491)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1194)
	at dev.flang.fuir.analysis.dfa.DFA.iteration(DFA.java:1159)
	at dev.flang.fuir.analysis.dfa.DFA.findFixPoint(DFA.java:1113)
	at dev.flang.fuir.analysis.dfa.DFA.dfa(DFA.java:1076)
	at dev.flang.fuir.analysis.dfa.DFA.new_fuir(DFA.java:923)
	at dev.flang.be.jvm.JVM.<init>(JVM.java:778)
	at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:191)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:507)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:1071)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:141)
	at dev.flang.util.Errors.runAndExit(Errors.java:935)
	at dev.flang.tools.Tool.run(Tool.java:141)
	at dev.flang.tools.Fuzion.main(Fuzion.java:626)


*** fatal errors encountered, stopping.

```

**Comment by michaellilltokiwa** [comment]
possibly related #1840
