### ISSUE TITLE
`StackOverfowError` after syntax error for single-line feature with post-condition. 

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#3042]
this happens: 
```
 > ./build/bin/fz -e "f i32 post true => 42"

command line:2:1: error 1: Syntax error: expected 'is', ':=' or '{', found end-of-file

^
While parsing: impl, parse stack: implFldOrRout, routOrField, feature, expr, exprs, block, unit


error 2: java.lang.StackOverflowError
	at dev.flang.ast.Expr.typeForInferencing(Expr.java:201)
	at dev.flang.ast.Expr.type(Expr.java:167)
	at dev.flang.ast.Expr.typeForInferencing(Expr.java:201)
	at dev.flang.ast.Expr.type(Expr.java:167)
	at dev.flang.ast.Expr.typeForInferencing(Expr.java:201)
	at dev.flang.ast.Expr.type(Expr.java:167)
	at dev.flang.ast.Expr.typeForInferencing(Expr.java:201)
```
And there are two problems: first, this should not crash with a StackOverflowError. Then, there should be some valid syntax to declare a single-line feature with a post condition.

**Comment by michaellilltokiwa** [comment]
The StackOverflowError does not occur anymore.

**Comment by simonvonhackewitz** [comment]
It works using braces: `fz -e "f i32 post {true} => 42"`

More complex example
```
❯ fz -e 'ex is {f i32 pre {for i in 1..5 do say "pre: {i**2}" else true} post {if true then true else false} => {42}; say f}' 
pre: 1
pre: 4
pre: 9
pre: 16
pre: 25
42
```

Can this be closed?
