### ISSUE TITLE
post condition in constructor

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#3140]
Post conditions used in constructors as follows
```
a(v i32)
  post
    v = 3
    result.v = 3
is

b(x i32) : a x-1
  post
   x = 4
   result.x = result.v+1
is

_ := a 3
_ := b 4
```
after #3138 still cause a crash in the middle end. 
```
 > ./build/bin/fz test_post_args.fz 

error 1: Found error clazz in set of clazzes in the IR even though no earlier errors were reported.  This can only be the result of a severe bug.

one error.

```

**Comment by michaellilltokiwa** [comment]
Now: 
```
error 1: java.lang.Error: check-condition failed: Clazz.java:1826 "(Errors.any() || i == o || i != null && i.isThisRef() && i.inheritsFrom(o));"
        at dev.flang.util.ANY.check(ANY.java:440)
        at dev.flang.fuir.Clazz.findOuter(Clazz.java:1826)
        at dev.flang.fuir.Clazz.replaceThisType(Clazz.java:591)
        at dev.flang.fuir.Clazz.handDown(Clazz.java:2003)
        at dev.flang.fuir.Clazz.resultClazz(Clazz.java:1708)
        at dev.flang.fuir.GeneratingFUIR.clazzArgClazz(GeneratingFUIR.java:1023)
        at dev.flang.fuir.analysis.AbstractInterpreter.args(AbstractInterpreter.java:423)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:604)
        at dev.flang.fuir.analysis.AbstractInterpreter.processCode(AbstractInterpreter.java:513)
        at dev.flang.fuir.analysis.AbstractInterpreter.processClazz(AbstractInterpreter.java:489)
        at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1460)
        at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:2935)
        at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:2891)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:422)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:372)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.accessSingleTarget(DFA.java:340)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:288)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:257)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:103)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:607)
        at dev.flang.fuir.analysis.AbstractInterpreter.processCode(AbstractInterpreter.java:513)
        at dev.flang.fuir.analysis.AbstractInterpreter.processClazz(AbstractInterpreter.java:489)
        at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1460)
        at dev.flang.fuir.analysis.dfa.DFA.iteration(DFA.java:1407)
        at dev.flang.fuir.analysis.dfa.DFA.findFixPoint(DFA.java:1291)
        at dev.flang.fuir.analysis.dfa.DFA.dfa(DFA.java:1267)
        at dev.flang.fuir.analysis.dfa.DFA.new_fuir(DFA.java:1155)
        at dev.flang.be.jvm.JVM.<init>(JVM.java:805)
        at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:189)
        at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:504)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$4(Fuzion.java:1068)
        at dev.flang.tools.Tool.lambda$run$0(Tool.java:142)
        at dev.flang.util.Errors.runAndExit(Errors.java:895)
        at dev.flang.tools.Tool.run(Tool.java:142)
        at dev.flang.tools.Fuzion.main(Fuzion.java:623)
```
Problem is that post condition is a feature which gets a `result feat.this` argument. But `feat` is not an outer of the post condition but rather a sibling. So it does not and can not find the outer for the this type.

**Comment by michaellilltokiwa** [comment]
@fridis I think the post condition probably needs to be defined as a child of a constructor?
