### ISSUE TITLE
require condition in parser for `match`

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#326]
This example:
```
> cat exMatchFail.fz
S is
  c bool | nil := true

  x => match c
    nil => "nil"
    bool   => "a"

_ := S.x
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c exMatchFail.fz
java.lang.Error: require-condition3 failed!
	at dev.flang.util.ANY.require(ANY.java:102)
	at dev.flang.ast.Match.<init>(Match.java:96)
	at dev.flang.parser.Parser.lambda$match$15(Parser.java:2433)
	at dev.flang.parser.Lexer.relaxLineAndSpaceLimit(Lexer.java:652)
	at dev.flang.parser.Parser.match(Parser.java:2423)
	at dev.flang.parser.Parser.term(Parser.java:2169)
	at dev.flang.parser.Parser.opTail(Parser.java:1946)
	at dev.flang.parser.Parser.opExpr(Parser.java:1926)
	at dev.flang.parser.Parser.expr(Parser.java:1887)
	at dev.flang.parser.Parser.exprInLine(Parser.java:1854)
	at dev.flang.parser.Parser.stmnt(Parser.java:2853)
	at dev.flang.parser.Parser.stmnts(Parser.java:2727)
	at dev.flang.parser.Parser.lambda$block$16(Parser.java:2652)
	at dev.flang.parser.Lexer.relaxLineAndSpaceLimit(Lexer.java:652)
	at dev.flang.parser.Parser.block(Parser.java:2651)
	at dev.flang.parser.Parser.implRout(Parser.java:3578)
	at dev.flang.parser.Parser.implFldOrRout(Parser.java:3607)
	at dev.flang.parser.Parser.routOrField(Parser.java:284)
	at dev.flang.parser.Parser.feature(Parser.java:240)
	at dev.flang.parser.Parser.stmnt(Parser.java:2853)
	at dev.flang.parser.Parser.stmnts(Parser.java:2727)
	at dev.flang.parser.Parser.lambda$block$16(Parser.java:2652)
	at dev.flang.parser.Lexer.relaxLineAndSpaceLimit(Lexer.java:652)
	at dev.flang.parser.Parser.block(Parser.java:2651)
	at dev.flang.parser.Parser.implRout(Parser.java:3577)
	at dev.flang.parser.Parser.implFldOrRout(Parser.java:3607)
	at dev.flang.parser.Parser.routOrField(Parser.java:284)
	at dev.flang.parser.Parser.feature(Parser.java:240)
	at dev.flang.parser.Parser.stmnt(Parser.java:2853)
	at dev.flang.parser.Parser.stmnts(Parser.java:2727)
	at dev.flang.parser.Parser.unit(Parser.java:177)
	at dev.flang.fe.SourceModule.parseFile(SourceModule.java:202)
	at dev.flang.fe.SourceModule.parseMain(SourceModule.java:174)
	at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:255)
	at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:176)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:606)
	at dev.flang.tools.Tool.run(Tool.java:168)
	at dev.flang.tools.Fuzion.main(Fuzion.java:305)
```

**Comment by fridis** [comment]
This is an indentation issue related to #268. 
This works: 
```
 > cat exMatchFail.fz
S is
  c bool | nil := true

  x => match c
        nil => "nil"
        bool   => "a"

_ := S.x
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c exMatchFail.fz
 > 

```
