### ISSUE TITLE
Missing `redef`causes require failure during AIR phase

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#327]
This fails to compile:
```
 > cat exRedefRequireFailed.fz
S is
  c i32 | nil := nil

  asString =>
    match c
      nil => "nil"
      i32 => "i"

say S
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c exRedefRequireFailed.fz -o=ex && ./ex

/home/fridi/fuzion/work/exRedefRequireFailed.fz:4:3: error 1: Redefinition must be declared using modifier 'redef'
  asString =>
--^
Feature that redefines existing feature: 'S'
original feature: 'Object.asString'
original feature defined in $FUZION/lib/Object.fz:31:3:
To solve this, if you did not intent to redefine an inherited feature, chose a different name for 'S'.  Otherwise, if you do want to redefine an inherited feature, add a 'redef' modifier before the declaration of 'S'.

java.lang.Error: require-condition1 failed!
	at dev.flang.util.ANY.require(ANY.java:82)
	at dev.flang.air.Clazzes.calledDynamically(Clazzes.java:512)
	at dev.flang.air.Clazzes.findClazzes(Clazzes.java:831)
	at dev.flang.air.Clazz$1.action(Clazz.java:1298)
	at dev.flang.ast.Stmnt.visitStatements(Stmnt.java:72)
	at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:123)
	at dev.flang.ast.AbstractMatch.visitStatements(AbstractMatch.java:123)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractAssign.visitStatements(AbstractAssign.java:140)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractFeature.visitStatements(AbstractFeature.java:1086)
	at dev.flang.air.Clazz.inspectCode(Clazz.java:1248)
	at dev.flang.air.Clazz.findAllClasses(Clazz.java:1292)
	at dev.flang.air.Clazzes.findAllClasses(Clazzes.java:421)
	at dev.flang.fuir.FUIR.<init>(FUIR.java:177)
	at dev.flang.opt.Optimizer.fuir(Optimizer.java:73)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:613)
	at dev.flang.tools.Tool.run(Tool.java:168)
	at dev.flang.tools.Fuzion.main(Fuzion.java:305)
```
while this runs fine, the only difference being 'redef' added:
```
 > cat exRedefRequireFailed2.fz
S is
  c i32 | nil := nil

  redef asString =>
    match c
      nil => "nil"
      i32 => "i"

say S
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c exRedefRequireFailed2.fz -o=ex && ./ex
nil
 > 
```

**Comment by fridis** [comment]
PR #1297 referenced wrong issue.
