### ISSUE TITLE
passing `java.lang.String[]` to Java method fails with `IllegalArgumentException`

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#330]
```
 > cat testJavaStringArray.fz
testJavaStringArray is
  rt := Java.java.lang.Runtime.getRuntime
  rt.exec "ls" [
    Java.java.lang.String.new ".",
    Java.java.lang.String.new "build" ]
  unit
 > ./build/bin/fz -unsafeIntrinsics=on -modules=java.base testJavaStringArray.fz

error 1: *** java.lang.IllegalArgumentException: argument type mismatch
Call stack:
fuzion.java.callVirtual<outcome<Java.java.lang.Process>>: $FUZION/lib/fuzion/java.fz:121:5:
    callV0<T> c n s thiz a
----^
Java.java.lang.ref Runtime.exec_Ljava_7_lang_7_String_s__u00005b_Ljava_7_lang_7_String_s_: /home/fridi/fuzion/work/build/bin/../modules/java.base/Java/java/lang/Runtime.fz:30:17:
    fuzion.java.callVirtual<outcome<Java.java.lang.Process>> "java.lang.Runtime" "exec" "(Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/Process;" Runtime.this [fuzion.java.stringToJavaObject arg0; fuzion.java.arrayToJavaObject<Java.java.lang.String> arg1]
----------------^
Java.java.lang.ref Runtime.exec: /home/fridi/fuzion/work/build/bin/../modules/java.base/Java/java/lang/Runtime.fz:115:5:
    exec_Ljava_7_lang_7_String_s__u00005b_Ljava_7_lang_7_String_s_ arg0 arg1
----^
testJavaStringArray: /home/fridi/fuzion/work/testJavaStringArray.fz:3:6:
  rt.exec "ls" [
-----^


java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at dev.flang.be.interpreter.JavaInterface.call(JavaInterface.java:428)
	at dev.flang.be.interpreter.Intrinsics.lambda$call$8(Intrinsics.java:256)
```

**Comment by fridis** [comment]
Here is a nicer example, works now:
```
 > cat testJavaStringArray.fz
testJavaStringArray : time.durations is

  js(s string) => Java.java.lang.String.new s

  exec(cmd Sequence Java.java.lang.String) =>
    match Java.java.lang.Runtime.getRuntime
              .exec__u00005b_Ljava_7_lang_7_String_s_ cmd
      e error => say "******* $e **********"
      p Java.java.lang.Process  => say "+++++++ {p.toString} ++++++++++"

  exec [ js "emacs" ,
         js "Hello.fz",
         js "hw12.fz"
       ]

  exec (Sequences.empty Java.java.lang.String)
 > ./build/bin/fz -unsafeIntrinsics=on -modules=java.base testJavaStringArray.fz
+++++++ Process[pid=17981, exitValue="not exited"] ++++++++++
******* error: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0 **********
```
