### ISSUE TITLE
partial function results in `NullPointerException` in JVM backend

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#3308]
This
```
f(x ()->unit) =>

t is
  a is
    q =>
    say (f a.this.q)

_ := t.a
```
causes this
```
 > ./build/bin/fz crash_jvm.fz

error 1: java.lang.NullPointerException: Cannot read field "_idInFUIR" because "<parameter1>" is null
	at dev.flang.fuir.FUIR.id(FUIR.java:234)
	at dev.flang.fuir.FUIR.clazzResultClazz(FUIR.java:486)
	at dev.flang.be.jvm.JVM.fieldExists(JVM.java:1595)
	at dev.flang.be.jvm.JVM$CompilePhase$2.compile(JVM.java:437)
	at dev.flang.be.jvm.JVM.lambda$createCode$0(JVM.java:934)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
	at dev.flang.be.jvm.JVM.createCode(JVM.java:927)
	at dev.flang.be.jvm.JVM.compile(JVM.java:914)
	at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:191)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:507)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:1071)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:141)
	at dev.flang.util.Errors.runAndExit(Errors.java:957)
	at dev.flang.tools.Tool.run(Tool.java:141)
	at dev.flang.tools.Fuzion.main(Fuzion.java:626)


*** fatal errors encountered, stopping.
one error.
```
but works for interpreter  and C backends: 
```
 > ./build/bin/fz -interpreter  crash_jvm.fz
unit
 > ./build/bin/fz -c  crash_jvm.fz && ./universe 
unit
```

**Comment by fridis** [comment]
Problem is earlier, with checks I get this during `air`
```
> PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -interpreter crash_jvm.fz

error 1: java.lang.Error: ensure-condition failed: AbstractFeature.java:1498 "(this == Types.f_ERROR || ancestor == Types.f_ERROR || Errors.any() || result != null);"
	at dev.flang.util.ANY.ensure(ANY.java:292)
	at dev.flang.ast.AbstractFeature.findInheritanceChain(AbstractFeature.java:1498)
	at dev.flang.air.Clazz.findRedefinition(Clazz.java:1011)
	at dev.flang.air.Clazz.lookup(Clazz.java:1212)
	at dev.flang.air.Clazzes.findClazzes(Clazzes.java:758)
	at dev.flang.air.Clazz$EV.action(Clazz.java:169)
	at dev.flang.ast.Expr.visitExpressions(Expr.java:338)
	at dev.flang.ast.AbstractCall.visitExpressions(AbstractCall.java:99)
	at dev.flang.ast.AbstractAssign.visitExpressions(AbstractAssign.java:139)
	at dev.flang.ast.AbstractFeature.visitExpressions(AbstractFeature.java:1594)
	at dev.flang.air.Clazz.inspectCode(Clazz.java:1534)
	at dev.flang.air.Clazz.findAllClasses(Clazz.java:1578)
	at dev.flang.air.Clazzes.findAllClasses(Clazzes.java:408)
	at dev.flang.fuir.FUIR.<init>(FUIR.java:187)
	at dev.flang.opt.Optimizer.fuir(Optimizer.java:73)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:506)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:1071)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:141)
	at dev.flang.util.Errors.runAndExit(Errors.java:957)
	at dev.flang.tools.Tool.run(Tool.java:141)
	at dev.flang.tools.Fuzion.main(Fuzion.java:626)


*** fatal errors encountered, stopping.

```
