### ISSUE TITLE
Precondition for division by `0` does not work 

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#3531]
See this (similar for JVM or C backends): 
```
 > ./build/bin/fz -interpreter -e "_ := 3/0"

error 1: *** java.lang.ArithmeticException: / by zero
Call stack:
i32.precall infix /: $MODULE/i32.fz:55:5:
    pre else
      // NYI: #3051 precondition inheritance does not work yet
      // remove this redundant precondition once #3051 is fixed
      safety: other != 0

universe: command line:1:7:
_ := 3/0




error 2: java.lang.ArithmeticException: / by zero
	at dev.flang.be.interpreter.Intrinsics.lambda$static$230(Intrinsics.java:1205)
	at dev.flang.be.interpreter.Executor.call(Executor.java:269)
	at dev.flang.be.interpreter.Executor.call(Executor.java:49)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:598)
	at dev.flang.fuir.analysis.AbstractInterpreter.processCode(AbstractInterpreter.java:505)
	at dev.flang.fuir.analysis.AbstractInterpreter.processClazz(AbstractInterpreter.java:481)

```
looks like this is related to #3051.

**Comment by michaellilltokiwa** [comment]
@fridis this was already fixed with #3517

```
/home/not_synced/fuzion (2024-08-13T19-23-18+02-00)130$ fz -interpreter -e "_ := 3/0"

error 1: FATAL FAULT `precondition`: safety: other != 0
Call stack:
fuzion.type.runtime.type.fault.type.install_default.λ.call#1: $MODULE/fuzion/runtime/fault.fz:38:7:
      fuzion.sys.fatal_fault kind msg

fuzion.runtime.fault.cause#1: $MODULE/eff/fallible.fz:35:6:
  => h e

fuzion.type.runtime.type.pre_fault.type.install_default.λ.call#1: $MODULE/fuzion/runtime/pre_fault.fz:39:7:
      fuzion.runtime.fault.cause ("precondition", msg)).default

fuzion.runtime.pre_fault.cause#1: $MODULE/eff/fallible.fz:35:6:
  => h e

fuzion.runtime.precondition_fault#1: $MODULE/fuzion/runtime/pre_fault.fz:58:42:
public precondition_fault(msg String) => pre_fault.cause msg

i32.pre infix /: $MODULE/i32.fz:58:7:
      safety: other != 0

i32.precall infix /: $MODULE/i32.fz:55:5:
    pre else
      // NYI: #3051 precondition inheritance does not work yet
      // remove this redundant precondition once #3051 is fixed
      safety: other != 0

universe: command line:1:7:
_ := 3/0


*** fatal errors encountered, stopping.
one error.
```
