### ISSUE TITLE
IndexOutOfBoundsException in Call.inferGenericsFromArgs()

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#356]
the example:
```
example is
  color : choice of red, green, blue.
�  color : choice of red, green, blue.
```
the error:
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.set(ArrayList.java:441)
        at dev.flang.ast.Call.inferGenericsFromArgs(Call.java:1435)
        at dev.flang.ast.Call.resolveTypes(Call.java:1674)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1282)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1274)
        at dev.flang.ast.Call.visit(Call.java:1033)
        at dev.flang.ast.Resolution.resolveType(Resolution.java:497)
        at dev.flang.ast.Call.lambda$resolveTypesOfActuals$2(Call.java:775)
        at dev.flang.ast.Feature.internalResolveTypes(Feature.java:1337)
        at dev.flang.ast.Resolution.resolveOne(Resolution.java:371)
        at dev.flang.ast.Resolution.resolve(Resolution.java:338)
        at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:259)
        at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:176)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:621)
        at dev.flang.tools.Tool.run(Tool.java:168)
        at dev.flang.tools.Fuzion.main(Fuzion.java:320)
```

**Comment by michaellilltokiwa** [comment]
another example:
```
ex =>

  a : choice<string, , i32> is
```

**Comment by michaellilltokiwa** [comment]
another example: 
```
ex =>
  a : choice is
  b : map string a is
```
