### ISSUE TITLE
Simple effect abort code causes backend crash

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#3599]
Try this, which is a condensed version of fuzion-lang.dev's `content/talks/examples/fosdem23_aijd_01_max_exc.fz`:
```
 > ./build/bin/fz -e 'effect.instate_self ()->effect.env.abort'

error 1: java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:103)
	at java.base/java.util.Stack.pop(Stack.java:85)
	at dev.flang.be.jvm.classfile.Expr$1.buildStackMapTable(Expr.java:606)
	at dev.flang.be.jvm.classfile.Expr$35.buildStackMapTable(Expr.java:2011)
	at dev.flang.be.jvm.classfile.Expr$35.buildStackMapTable(Expr.java:2011)
```
C and interpreter backends have similar problems with this.

**Comment by michaellilltokiwa** [comment]
fixed #3640
