### ISSUE TITLE
Small example using `infix ∈` results in pop on empty stack

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#3613]
After this patch
```
 > git diff src/dev/flang/ast/Call.java
diff --git a/src/dev/flang/ast/Call.java b/src/dev/flang/ast/Call.java
index 8e0c2a384..13f747b7c 100644
--- a/src/dev/flang/ast/Call.java
+++ b/src/dev/flang/ast/Call.java
@@ -1559,7 +1559,7 @@ public class Call extends AbstractCall
                                           _target.typeForCallTarget());
         var t0 = t;
         t = t.replace_this_type_by_actual_outer(inner,
-                                                (from,to) -> AstErrors.illegalOuterRefTypeInCall(this, t0, from, to),
+                                                //    (from,to) -> AstErrors.illegalOuterRefTypeInCall(this, t0, from, to),
                                                 context);
       }
     return t;

```
the example
```
_ := "" ∈ s
s : container.Set String is
```
results in 
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz idiom119ex_emptystack3.fz

error 1: java.lang.Error: require-condition1 failed: AbstractInterpreter.java:388 "(clazzHasUnitValue(cl) || stack.size() > 0, !containsVoid(stack));"
	at dev.flang.util.ANY.require(ANY.java:116)
	at dev.flang.fuir.analysis.AbstractInterpreter.pop(AbstractInterpreter.java:388)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:609)
	at dev.flang.fuir.analysis.AbstractInterpreter.processCode(AbstractInterpreter.java:512)
	at dev.flang.fuir.analysis.AbstractInterpreter.processClazz(AbstractInterpreter.java:488)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1449)
	at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:2826)
	at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:2782)
	at dev.flang.fuir.analysis.dfa.DFA.dfa(DFA.java:1250)
	at dev.flang.fuir.analysis.dfa.DFA.new_fuir(DFA.java:1121)
	at dev.flang.be.jvm.JVM.<init>(JVM.java:796)
	at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:191)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:507)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$4(Fuzion.java:1071)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:142)
	at dev.flang.util.Errors.runAndExit(Errors.java:878)
	at dev.flang.tools.Tool.run(Tool.java:142)
	at dev.flang.tools.Fuzion.main(Fuzion.java:626)


*** fatal errors encountered, stopping.
one error.

```

**Comment by michaellilltokiwa** [comment]
meanwhile fixed
