### ISSUE TITLE
`choice` with overlapping generics cause `java.lang.Error: check-condition failed`

### ISSUE THREAD

**Issue by simonvonhackewitz** [tokiwa-software/fuzion#3757]
```
> cat /tmp/test.fz
my_string : String is
my_choice2 : choice String my_string is
mc2 my_choice2 := "str" // 2. should flag an error: generics must be disjoint
```
```
> FUZION_DISABLE_ANSI_ESCAPES=true fz /tmp/test.fz

error 1: java.lang.Error: check-condition failed: CodeGen.java:202 "(v.type()                instanceof PrimitiveType pt && pt == _types.resultType(type) || v.type()                instanceof ClassType     jt && _types.resultType(type) instanceof ClassType     ct && (_fuir.clazzIsRef(type) /* we do not check exact reference assignability here */ || jt.sameAs(ct)          /* but value or choice types must be the same!        */ || jt == NULL_TYPE));"
        at dev.flang.util.ANY.check(ANY.java:440)
        at dev.flang.be.jvm.CodeGen.drop(CodeGen.java:202)
        at dev.flang.be.jvm.CodeGen.drop(CodeGen.java:56)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:587)
        at dev.flang.fuir.analysis.AbstractInterpreter.processCode(AbstractInterpreter.java:512)
        at dev.flang.fuir.analysis.AbstractInterpreter.processClazz(AbstractInterpreter.java:488)
        at dev.flang.be.jvm.JVM.codeForRoutine(JVM.java:1254)
        at dev.flang.be.jvm.JVM.code(JVM.java:962)
        at dev.flang.be.jvm.JVM$CompilePhase$3.compile(JVM.java:460)
        at dev.flang.be.jvm.JVM.lambda$createCode$0(JVM.java:938)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:792)
        at dev.flang.be.jvm.JVM.createCode(JVM.java:931)
        at dev.flang.be.jvm.JVM.compile(JVM.java:918)
        at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:191)
        at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:507)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$4(Fuzion.java:1071)
        at dev.flang.tools.Tool.lambda$run$0(Tool.java:142)
        at dev.flang.util.Errors.runAndExit(Errors.java:895)
        at dev.flang.tools.Tool.run(Tool.java:142)
        at dev.flang.tools.Fuzion.main(Fuzion.java:626)

*** fatal errors encountered, stopping.
one error.
```

Example is part of test `nested_choice_negative`.

**Comment by fridis** [comment]
This maybe needs some explanation: value types are always disjoint to all other types, so your `my_string` is very different to `String`. 
Things would be different if `My_String` was a `ref`, then —I think— we currently forbid this case. However, this is not strictly required, we could still distinguish the case where the static type of a value assigned to the choice type assignable to `My_String` from when it is only assignable to `String`, but the compiler can no longer optimize the `tag` in this case since the static type `String` may still be a dynamic type `My_String`.
