### ISSUE TITLE
JVM backend crashes when non-`ref` value is passed to `ref`/`this` type argument defined in non-`ref` feature

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#4248]
When debugging the original problem behind #4247, I ran into this problem that is probably related to #3731:
```
e is
  me => e.this
  type.x(a e.this) => $a.me

p ref : e is

f : p is

_ := p.type.x f
```
which crashes the JVM backend
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz test_box2.fz

error 1: java.lang.Error: require-condition1 failed: Expr.java:1904 "(!type.isPrimitive());"
	at dev.flang.util.ANY.require(ANY.java:101)
	at dev.flang.be.jvm.classfile.Expr.checkcast(Expr.java:1904)
	at dev.flang.be.jvm.CodeGen.access(CodeGen.java:377)
	at dev.flang.be.jvm.CodeGen.call(CodeGen.java:278)
	at dev.flang.be.jvm.CodeGen.call(CodeGen.java:56)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:612)
	at dev.flang.fuir.analysis.AbstractInterpreter.processCode(AbstractInterpreter.java:514)
	at dev.flang.fuir.analysis.AbstractInterpreter.processClazz(AbstractInterpreter.java:490)
	at dev.flang.be.jvm.JVM.codeForRoutine(JVM.java:1372)
	at dev.flang.be.jvm.JVM.code(JVM.java:968)
	at dev.flang.be.jvm.JVM$CompilePhase$3.compile(JVM.java:459)
	at dev.flang.be.jvm.JVM.lambda$createCode$0(JVM.java:944)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
	at dev.flang.be.jvm.JVM.createCode(JVM.java:937)
	at dev.flang.be.jvm.JVM.compile(JVM.java:924)
	at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:181)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:499)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$4(Fuzion.java:1064)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:142)
	at dev.flang.util.Errors.runAndExit(Errors.java:903)
	at dev.flang.tools.Tool.run(Tool.java:142)
	at dev.flang.tools.Fuzion.main(Fuzion.java:618)


*** fatal errors encountered, stopping.
one error.
```
The likely problem is a missing `box` operation on `f` when it is passed to `p.type.x`.

**Comment by fridis** [comment]
The problem is that in the call `a.me` within `p.type` the result is `f` which is not boxed and then used as `p`. 
A solution might be to box the call result if it is `.this`. 
A similar problem occurs if the result type has a `.this` type as type parameter, e.g., `option e.this`.
