### ISSUE TITLE
AoC: Crash of `fz` in small example using type constraints in precondition

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#4353]
Try this:
```
Sequence.unzip2(A type)
pre
  T : tuple A
=>
  map x->x.values.0

_ := [tuple 42].unzip2 i32
```
it produces a crash:
```
> PRECONDITIONS=true POSTCONDITIONS=true /home/fridi/fuzion/clean/fuzion/build//bin/fz -modules=terminal crash.fz

error 1: java.lang.Error: require-condition1 failed: GeneratingFUIR.java:562 "(Errors.any() || !thiz.dependsOnGenerics(), !thiz.isThisType());"
	at dev.flang.util.ANY.require(ANY.java:116)
	at dev.flang.fuir.GeneratingFUIR.type2clazz(GeneratingFUIR.java:562)
	at dev.flang.fuir.Clazz.handDown(Clazz.java:2005)
	at dev.flang.fuir.Clazz.resultClazz(Clazz.java:1721)
	at dev.flang.fuir.GeneratingFUIR.calledInner(GeneratingFUIR.java:2626)
	at dev.flang.fuir.GeneratingFUIR.accessedClazz(GeneratingFUIR.java:2567)
	at dev.flang.fuir.GeneratingFUIR.accessedClazz(GeneratingFUIR.java:2541)
	at dev.flang.fuir.analysis.AbstractInterpreter2.process(AbstractInterpreter2.java:603)
	at dev.flang.fuir.analysis.AbstractInterpreter2.processCode(AbstractInterpreter2.java:511)
	at dev.flang.fuir.analysis.AbstractInterpreter2.processClazz(AbstractInterpreter2.java:489)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1524)
	at dev.flang.fuir.analysis.dfa.DFA.iteration(DFA.java:1471)
	at dev.flang.fuir.analysis.dfa.DFA.findFixPoint(DFA.java:1300)
	at dev.flang.fuir.analysis.dfa.DFA.dfa(DFA.java:1276)
	at dev.flang.fuir.analysis.dfa.DFA.new_fuir(DFA.java:1142)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:499)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$4(Fuzion.java:1064)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:142)
	at dev.flang.util.Errors.runAndExit(Errors.java:903)
	at dev.flang.tools.Tool.run(Tool.java:142)
	at dev.flang.tools.Fuzion.main(Fuzion.java:618)


*** fatal errors encountered, stopping.
one error.

```

**Comment by michaellilltokiwa** [comment]
same problem:
```
Sequence.unzip2(A type)
pre
  T : tuple A
=>
  first.get.values.0

_ := [tuple 42].unzip2 String
```
