### ISSUE TITLE
docs do not build anymore

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#4368]
```
/home/not_synced/fuzion (2024-12-02T13-44-51+01-00)$ make debug_api_docs 
Exception in thread "main" java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: base/num+(no+arguments)/ry?+(one+argument)
        at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:131)
        at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:77)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:312)
        at java.base/java.nio.file.Path.resolve(Path.java:516)
        at dev.flang.tools.docs.Docs.lambda$run$17(Docs.java:365)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1716)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
        at dev.flang.tools.docs.Docs.run(Docs.java:362)
        at dev.flang.tools.docs.Docs.main(Docs.java:416)

```

**Comment by simonvonhackewitz** [comment]
I can not reproduce this.
