### ISSUE TITLE
printing a `type` results in diverse problems

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#447]
Using this example
```
 > cat printtype.fz
printtype is

  inner is

  test := i32.type
  say test
  test := printtype.type
  say "A:"
  say test
  test := printtype.inner.type
  say "B:"
  say test
  test := fuzion.java.type
  say "C:"
  say test
 >
```
results in a CHECK-failure when using the interpreter
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz printtype.fz
Type of 'i32'
A:
Type of 'printtype'
B:

error 1: *** java.lang.Error: check-condition failed: dev.flang.be.interpreter.ValueWithClazz:clazz:90
Call stack:
fuzion.std.out.print: $FUZION/lib/fuzion/std/out.fz:31:13:
    write s.asString.utf8.asArray
------------^
io.ref defaultPrintToOut.print: $FUZION/lib/io/out.fz:60:29:
  print(s Object) => stdout.print s
----------------------------^
io.ref defaultPrintToOut.println: $FUZION/lib/io/printEffect.fz:60:5:
    print s
----^
io.out.println: $FUZION/lib/io/printEffect.fz:41:7:
    p.println s
------^
say: $FUZION/lib/say.fz:31:29:
say(s ref Object) => io.out.println s
----------------------------^
printtype: /home/fridi/fuzion/work/printtype.fz:12:3:
  say test
--^


java.lang.Error: check-condition failed: dev.flang.be.interpreter.ValueWithClazz:clazz:90
	at dev.flang.util.ANY.check(ANY.java:383)
	at dev.flang.be.interpreter.ValueWithClazz.clazz(ValueWithClazz.java:90)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:319)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:642)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:642)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:647)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:333)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:369)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:925)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:802)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:322)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:333)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:369)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:925)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:802)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:322)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:369)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:642)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:642)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:333)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:369)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:925)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:802)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:322)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:369)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:642)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:486)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:642)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:333)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:369)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:925)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:802)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:322)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:333)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:369)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:925)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:802)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:322)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:369)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:925)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:802)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:231)
	at dev.flang.tools.Fuzion$Backend$1.process(Fuzion.java:96)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:309)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:743)
	at dev.flang.tools.Tool.run(Tool.java:153)
	at dev.flang.tools.Fuzion.main(Fuzion.java:423)
 >
```
and an uninitalized field when using the C backend:
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c printtype.fz

error 1: reading uninitialized field i32.#type.name from instance of i32.#type
fields available:
  

one error.
 >
```

**Comment by fridis** [comment]
This was fixed by recent work on type instances such as 460ef235592e26c5ee2b9aa0b36a5ded5868b0db:

```
 > cat ../../work/printtype2.fz 
printtype is

  inner is

  test := i32.type
  say test
  test := printtype.type
  say "A:"
  say test
  test := printtype.inner.type
  say "B:"
  say test
  test := fuzion.java.type
  say "C:"
  say test
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz ../../work/printtype2.fz 
Type of 'i32'
A:
Type of 'printtype'
B:
Type of 'printtype.inner'
C:
Type of 'fuzion.java'
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c ../../work/printtype2.fz 
 > ./printtype
Type of 'i32'
A:
Type of 'printtype'
B:
Type of 'printtype.inner'
C:
Type of 'fuzion.java'
```
