### ISSUE TITLE
GeneratingFUIR.java:559 "(Errors.any() || !thiz.dependsOnGenerics(), !thiz.isThisType());"

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#4512]
```
ex_buffered_writer =>

  _ := stdout ! ()->
    x := array u8 1023 i->0x61
    y := array u8 2049 i->0x62
    z := array u8  128 i->0x63

    _ := stdout.env.write x
    _ := stdout.env.write y
    _ := stdout.env.write z
    _ := stdout.env.flush



write_provider : io.Write_Provider is
  redef write (b Sequence u8) outcome unit =>
    yak (String.from_bytes b)

stdout : io.buffered.writer write_provider 1024 is

_ := ex_buffered_writer

```

**Comment by simonvonhackewitz** [comment]
Another example that causes this error
```
values array codepoint := ["A", "1", "b", "?", "X", "4"]

classify Unary String codepoint := c -> c.is_ascii_letter ? "letter" : c.is_ascii_digit ? "digit" : "other"

say (values.group_map_reduce String i32 classify (_->1) (+))
```
```
❯ fz ~/playground/2025-01-23_group_map_reduce_example.fz

error 1: java.lang.Error: require-condition2 failed: GeneratingFUIR.java:555 "(Errors.any() || !thiz.dependsOnGenerics(), !thiz.isThisType());"
        at dev.flang.util.ANY.require(ANY.java:117)
        at dev.flang.fuir.GeneratingFUIR.type2clazz(GeneratingFUIR.java:555)
        at dev.flang.fuir.GeneratingFUIR.type2clazz(GeneratingFUIR.java:562)
        at dev.flang.fuir.Clazz.handDown(Clazz.java:1945)
        .
        .
        .
```
