### ISSUE TITLE
fuzion.sys.Pointer.as_string crashes DFA (if fuzion.sys.Pointer is modeled as SysArray)

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#4514]
With the following patch:
```diff
diff --git a/modules/base/src/fuzion/sys/pipe.fz b/modules/base/src/fuzion/sys/pipe.fz
index 8fbd3e222..c863c7701 100644
--- a/modules/base/src/fuzion/sys/pipe.fz
+++ b/modules/base/src/fuzion/sys/pipe.fz
@@ -30,7 +30,7 @@ module pipe is
   #
   module read(
     # the descriptor
-    desc i64,
+    desc fuzion.sys.Pointer,
     # the internal array data representing the container for the bytes to be read
     file_array fuzion.sys.Pointer,
     # the length of the array that represents the file bytes
@@ -40,7 +40,7 @@ module pipe is
   #
   module write(
     # the descriptor
-    desc i64,
+    desc fuzion.sys.Pointer,
     # the internal array data representing the content bytes to write
     content fuzion.sys.Pointer,
     # the length of the internal array representing the content
@@ -51,4 +51,4 @@ module pipe is
   #
   module close(
               # descriptor
-              desc i64) i32 => intrinsic
+              desc fuzion.sys.Pointer) i32 => intrinsic
diff --git a/modules/base/src/fuzion/sys/process.fz b/modules/base/src/fuzion/sys/process.fz
index bc9aa1539..f894826f8 100644
--- a/modules/base/src/fuzion/sys/process.fz
+++ b/modules/base/src/fuzion/sys/process.fz
@@ -34,7 +34,7 @@ module process is
 
   # wait for process to exit
   #
-  module wait(p i64) i32 => intrinsic
+  module wait(p fuzion.sys.Pointer) i32 => intrinsic
 
   # NYI send_signal(p i64, signal i32) unit => intrinsic
   # NYI is_alive(p i64) unit => intrinsic
diff --git a/modules/base/src/os/process.fz b/modules/base/src/os/process.fz
index 6e94d936f..1865ea994 100644
--- a/modules/base/src/os/process.fz
+++ b/modules/base/src/os/process.fz
@@ -23,7 +23,7 @@
 
 # type denoting a started process
 #
-module:public process(module id, std_in, std_out, std_err i64) : property.equatable, property.orderable is
+module:public process(module id, std_in, std_out, std_err fuzion.sys.Pointer) : property.equatable, property.orderable is
 
   # how many bytes are read at a time
   # POSIX.1 requires PIPE_BUF to be at least 512 bytes
@@ -31,6 +31,11 @@ module:public process(module id, std_in, std_out, std_err i64) : property.equata
   pipe_buffer_size := 4096
 
 
+  # this in order to implement orderable
+  #
+  uid := unique_id
+
+
   # predefined read provider for reading from
   # standard out of the process
   #
@@ -51,7 +56,7 @@ module:public process(module id, std_in, std_out, std_err i64) : property.equata
 
   # read bytes from standard out
   #
-  read_provider(desc i64) : io.Read_Provider is
+  read_provider(desc fuzion.sys.Pointer) : io.Read_Provider is
     redef read(count i32) choice (array u8) io.end_of_file error =>
       arr := array u8 pipe_buffer_size i->0
       res := fuzion.sys.pipe.read desc arr.internal_array.data arr.count
@@ -67,7 +72,7 @@ module:public process(module id, std_in, std_out, std_err i64) : property.equata
 
   # write bytes to standard in
   #
-  write_provider (desc i64) : io.Write_Provider is
+  write_provider (desc fuzion.sys.Pointer) : io.Write_Provider is
     redef write (bytes Sequence u8) outcome unit =>
       if (fuzion.sys.pipe.write desc bytes.as_array.internal_array.data bytes.count) = -1
         error "error while writing"
@@ -84,7 +89,7 @@ module:public process(module id, std_in, std_out, std_err i64) : property.equata
 
   # helper function
   #
-  write_bytes (desc i64, bytes Sequence u8) outcome i32
+  write_bytes (desc fuzion.sys.Pointer, bytes Sequence u8) outcome i32
   pre debug: bytes.count > 0
   =>
     bytes
@@ -176,10 +181,10 @@ module:public process(module id, std_in, std_out, std_err i64) : property.equata
 
   # equality
   #
-  public redef fixed type.equality(a, b process.this) => a.id = b.id
+  public redef fixed type.equality(a, b process.this) => a.uid = b.uid
 
 
   # lteq
   #
   public redef fixed type.lteq(a, b process.this) bool =>
-    a.id <= b.id
+    a.uid <= b.uid
diff --git a/modules/base/src/os/processes.fz b/modules/base/src/os/processes.fz
index b9db9a63c..30be67d98 100644
--- a/modules/base/src/os/processes.fz
+++ b/modules/base/src/os/processes.fz
@@ -113,8 +113,8 @@ install_default =>
       # NULL is also used to terminate the environment variables data structure.
       env_str := sys.c_string ((String.type.join env_var_strings (codepoint 0)) + (codepoint 0))
 
-      res_data := array i64 4 i->0
-      if (sys.process.create arg_data.internal_array.data arg_data.count env_data.internal_array.data env_data.count res_data.internal_array.data args_str env_str) = -1
+      res_data := fuzion.sys.internal_array_init fuzion.sys.Pointer 4
+      if (sys.process.create arg_data.internal_array.data arg_data.count env_data.internal_array.data env_data.count res_data.data args_str env_str) = -1
         error "*** error creating process ***"
       else
         os.process res_data[0] res_data[1] res_data[2] res_data[3]
```
and 
`make no-java && make -C build/tests/process`
we get
```
> 
> error 1: java.lang.Error: check-condition1 failed: DFA.java:2900 "(((k >> (18*2+10)) & 0x3FFFF) == k1, ((k >> (18  +10)) & 0x3FFFF) == k2, ((k >> (     10)) & 0x3FFFF) == k3, ((k               & 0x003FF) == k4));"
>       at dev.flang.util.ANY.check(ANY.java:500)
>       at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:2900)
>       at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:396)
>       at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:346)
>       at dev.flang.fuir.analysis.dfa.DFA$Analyze.accessSingleTarget(DFA.java:314)
>       at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:257)
>       at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:231)
>       at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:96)
>       at dev.flang.fuir.analysis.AbstractInterpreter2.process(AbstractInterpreter2.java:598)
>       at dev.flang.fuir.analysis.AbstractInterpreter2.processCode(AbstractInterpreter2.java:505)
>       at dev.flang.fuir.analysis.AbstractInterpreter2.processClazz(AbstractInterpreter2.java:483)
>       at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1522)
>       at dev.flang.fuir.analysis.dfa.DFA.iteration(DFA.java:1469)
>       at dev.flang.fuir.analysis.dfa.DFA.findFixPoint(DFA.java:1298)
>       at dev.flang.fuir.analysis.dfa.DFA.dfa(DFA.java:1274)
>       at dev.flang.fuir.analysis.dfa.DFA.new_fuir(DFA.java:1140)
>       at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:496)
>       at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$4(Fuzion.java:1062)
>       at dev.flang.tools.Tool.lambda$run$0(Tool.java:142)
>       at dev.flang.util.Errors.runAndExit(Errors.java:903)
>       at dev.flang.tools.Tool.run(Tool.java:142)
>       at dev.flang.tools.Fuzion.main(Fuzion.java:615)
> 
> *** fatal errors encountered, stopping.
> one error.
*** FAILED err on test_process.fz

```

**Comment by michaellilltokiwa** [comment]
This is due to makeUnique missing for the SysArray.

**Comment by michaellilltokiwa** [comment]
fixed by #4825
