### ISSUE TITLE
Assigning type value to field before use results in crash

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#456]
The following small example shows that using a type as a (boxed) argument in a call to `say` works, while assigning a type value to a field `x` before passing it to the call to `say` results in an error:

```
 > cat testTypes.fz
testTypes is
  t is
  say (testTypes.t.type)     # works
  x := testTypes.t.type
  say x                      # crashes
 > ./build/bin/fz testTypes.fz
Type of 'testTypes.t'

error 1: *** java.lang.NullPointerException: Cannot invoke "dev.flang.be.interpreter.Callable.call(java.util.ArrayList)" because "<local19>" is null
Call stack:
fuzion.std.out.print: $FUZION/lib/fuzion/std/out.fz:31:13:
    write s.asString.utf8.asArray
------------^
io.ref defaultPrintToOut.print: $FUZION/lib/io/out.fz:60:29:
  print(s Object) => stdout.print s
----------------------------^
io.ref defaultPrintToOut.println: $FUZION/lib/io/printEffect.fz:60:5:
    print s
----^
io.out.println: $FUZION/lib/io/printEffect.fz:41:7:
    p.println s
------^
say: $FUZION/lib/say.fz:31:29:
say(s ref Object) => io.out.println s
----------------------------^
testTypes: /home/fridi/fuzion/work/testTypes.fz:5:3:
  say x
--^


java.lang.NullPointerException: Cannot invoke "dev.flang.be.interpreter.Callable.call(java.util.ArrayList)" because "<local19>" is null
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:331)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:652)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:301)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:652)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:301)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:657)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:301)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:342)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:379)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:935)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:812)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:331)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:342)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:379)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:935)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:812)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:331)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:379)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:652)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:301)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:652)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:301)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:342)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:379)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:935)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:812)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:331)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:379)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:652)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:301)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:496)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:652)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:301)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:342)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:379)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:935)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:812)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:331)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:342)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:379)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:935)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:812)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:331)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:379)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:935)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:812)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:236)
	at dev.flang.tools.Fuzion$Backend$1.process(Fuzion.java:96)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:309)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:743)
	at dev.flang.tools.Tool.run(Tool.java:153)
	at dev.flang.tools.Fuzion.main(Fuzion.java:423)
```

**Comment by fridis** [comment]
For the C backend, this was solved with 4991552759ced42c81cc32ee546cb82c97ba1c39.
