### ISSUE TITLE
c-backend: no member named 'vref'; interpreter: require-condition1 Instance:storeNonRef:332

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#492]
```
ex is
  my_choice : choice string f64 is
  map_res(O1, O2 type, o1 O1, mapper O1 -> outcome O2) outcome O2 is
    mapper o1
  x := map_res string my_choice "" (x -> x)
```
both backends fail:
```
sam@debian /home/not_synced/fuzion (lib/modules/nom)$ fz  ~/playground/test.fz 

error 1: *** java.lang.Error: require-condition1 failed: dev.flang.be.interpreter.Instance:storeNonRef:332
Call stack:
ex.map_res<string, ex.my_choice>: /home/sam/playground/test.fz:5:5:
    mapper o1
----^
ex: /home/sam/playground/test.fz:6:8:
  x := map_res string my_choice "" (x -> x)
-------^


java.lang.Error: require-condition1 failed: dev.flang.be.interpreter.Instance:storeNonRef:332
        at dev.flang.util.ANY.require(ANY.java:78)
        at dev.flang.be.interpreter.Instance.storeNonRef(Instance.java:332)
        at dev.flang.be.interpreter.Interpreter.setNonRefField(Interpreter.java:1147)
        at dev.flang.be.interpreter.Interpreter.setFieldSlot(Interpreter.java:1360)
        at dev.flang.be.interpreter.Interpreter.setChoiceField(Interpreter.java:995)
        at dev.flang.be.interpreter.Interpreter.tag(Interpreter.java:271)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:576)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
        at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:920)
        at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
        at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:920)
        at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
        at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:920)
        at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
        at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:231)
        at dev.flang.tools.Fuzion$Backend$1.process(Fuzion.java:96)
        at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:343)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:788)
        at dev.flang.tools.Tool.run(Tool.java:153)
        at dev.flang.tools.Fuzion.main(Fuzion.java:463)
```
```
sam@debian /home/not_synced/fuzion (lib/modules/nom)1$ fz-c  ~/playground/test.fz 
/home/sam/.cache/fz_c_out.c:792:20: error: no member named 'vref' in 'union fzT__L115outcome_l___u_choice_g::(unnamed at /home/sam/.cache/fz_c_out.c:544:3)'
    fzM_0.fzChoice.vref = (fzT__RObject*)fzCur.fzF_0_x;
    ~~~~~~~~~~~~~~ ^
1 error generated.

error 1: C backend: C compiler failed
C compiler call 'clang -O3 -lm -lpthread -o /home/sam/.cache/fz_c_out /home/sam/.cache/fz_c_out.c' failed with exit code '1'

one error.
sam@debian /home/not_synced/fuzion (lib/modules/nom)1$ 
```

**Comment by michaellilltokiwa** [comment]
this issue seems related: #459
