### ISSUE TITLE
possibility to declare none disjoint choice elements via generics

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#577]
No errors in the front end are given by this code:
```
test is
  a(T type, b choice T i32) is
    match b
      t T => say "t"
      i32 i32 => say "i"

  a i32 2

  unit
```
```
sam@debian /home/not_synced/fuzion (main)$ fz ~/playground/test.fz

error 1: *** java.lang.Error: check-condition failed: dev.flang.air.Clazz:getChoiceTag:1537
Call stack:


java.lang.Error: check-condition failed: dev.flang.air.Clazz:getChoiceTag:1537
        at dev.flang.util.ANY.check(ANY.java:383)
        at dev.flang.air.Clazz.getChoiceTag(Clazz.java:1537)
        at dev.flang.be.interpreter.Interpreter.setChoiceField(Interpreter.java:976)
        at dev.flang.be.interpreter.Interpreter.tag(Interpreter.java:271)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:576)
        at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:648)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
        at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:920)
        at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
        at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:231)
        at dev.flang.tools.Fuzion$Backend$1.process(Fuzion.java:101)
        at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:356)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:827)
        at dev.flang.tools.Tool.run(Tool.java:153)
        at dev.flang.tools.Fuzion.main(Fuzion.java:476)
```
```
sam@debian /home/not_synced/fuzion (main)127$ fz-c ~/playground/test.fz
java.lang.Error: check-condition failed: dev.flang.air.Clazz:getChoiceTag:1537
        at dev.flang.util.ANY.check(ANY.java:383)
        at dev.flang.air.Clazz.getChoiceTag(Clazz.java:1537)
        at dev.flang.fuir.FUIR.clazzChoiceTag(FUIR.java:641)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:632)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:442)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:408)
        at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:867)
        at dev.flang.fuir.analysis.dfa.DFA.iteration(DFA.java:832)
        at dev.flang.fuir.analysis.dfa.DFA.findFixPoint(DFA.java:795)
        at dev.flang.fuir.analysis.dfa.DFA.dfa(DFA.java:777)
        at dev.flang.fuir.analysis.dfa.DFA.new_fuir(DFA.java:719)
        at dev.flang.be.c.C.<init>(C.java:497)
        at dev.flang.tools.Fuzion$Backend$2.process(Fuzion.java:133)
        at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:356)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:827)
        at dev.flang.tools.Tool.run(Tool.java:153)
        at dev.flang.tools.Fuzion.main(Fuzion.java:476)
```

**Comment by fridis** [comment]
This still does not work. My preference on how this should be handled:

- it should be allowed to have ambiguous choices as a result of type parameters like in this case
- it should, be flagged as an error to perform an assignment of such an ambiguous type to a choice, i.e., passing `2` as argument to `(a i32).b`:
```
  a i32 2                # causes error
  x choice i32 i32 := 2  # causes error
```
- it should, however, be possible to do this:
```
left(T type, b T  ) choice T i32 is b
rite(T type, i i32) choice T i32 is i
a (left i32 42)        # will print `t`
a (rite i32 4711)      # will print `i`
```

**Comment by michaellilltokiwa** [comment]
yields an error in frontend now:
```

/home/sam/playground/test.fz:7:9: error 1: Actual type parameters to choice type must be disjoint types
  a i32 2
--------^
The following types have overlapping values:
'i32'
'i32'

one error.

```
