### ISSUE TITLE
Inheriting from outer feature results in NullPointerException when type feature is used

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#624]
See this example:

```
 > cat test_crash.fz 
test_equals : t =>
  equals X X

_ := test_equals

t is
  X is
 > ./build/bin/fz test_crash.fz 
java.lang.NullPointerException: Cannot invoke "dev.flang.ast.AbstractFeature.thisType()" because "<local2>" is null
	at dev.flang.air.Clazz.typeClazz(Clazz.java:1950)
	at dev.flang.air.Clazz.typeClazz(Clazz.java:1950)
	at dev.flang.air.Clazz.determineResultClazz(Clazz.java:1975)
	at dev.flang.air.Clazz.dependencies(Clazz.java:408)
	at dev.flang.air.Clazzes.create(Clazzes.java:373)
	at dev.flang.air.Clazzes.clazzWithSpecificOuter(Clazzes.java:1177)
	at dev.flang.air.Clazz.lookup(Clazz.java:1076)
	at dev.flang.air.Clazzes.findClazzes(Clazzes.java:855)
	at dev.flang.air.Clazz$1.action(Clazz.java:1314)
	at dev.flang.ast.Stmnt.visitStatements(Stmnt.java:72)
	at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:123)
	at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:121)
	at dev.flang.ast.AbstractAssign.visitStatements(AbstractAssign.java:140)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractFeature.visitStatements(AbstractFeature.java:1183)
	at dev.flang.air.Clazz.inspectCode(Clazz.java:1264)
	at dev.flang.air.Clazz.findAllClasses(Clazz.java:1308)
	at dev.flang.air.Clazzes.findAllClasses(Clazzes.java:440)
	at dev.flang.fuir.FUIR.<init>(FUIR.java:201)
	at dev.flang.opt.Optimizer.fuir(Optimizer.java:73)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:367)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:832)
	at dev.flang.tools.Tool.run(Tool.java:153)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)

```

This is likely related to #579/#578.

**Comment by fridis** [comment]
updated examle:
```
 > cat ex_624.fz 
test_equals : t =>
  equals X X

_ := test_equals

t is
  X : equatable is
     type.equality(a,b X.this.type) => true
```
resuults in crash:
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz ex_624.fz 

error 1: java.lang.Error: require-condition1 failed: dev.flang.ast.AbstractFeature:typeFeature:865
	at dev.flang.util.ANY.require(ANY.java:78)
	at dev.flang.ast.AbstractFeature.typeFeature(AbstractFeature.java:865)
	at dev.flang.ast.AbstractType.typeType(AbstractType.java:1065)
	at dev.flang.ast.AbstractType.typeType(AbstractType.java:1078)
	at dev.flang.ast.AbstractType.typeType(AbstractType.java:1039)
	at dev.flang.air.Clazz.typeClazz(Clazz.java:2043)
	at dev.flang.air.Clazz.determineResultClazz(Clazz.java:2102)
	at dev.flang.air.Clazz.dependencies(Clazz.java:415)
	at dev.flang.air.Clazzes.create(Clazzes.java:389)
	at dev.flang.air.Clazzes.clazzWithSpecificOuter(Clazzes.java:1226)
```
