### ISSUE TITLE
type parameter replacement goes too far

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#659]
```
test =>
  parser(I type) ref is
    parse(i i32) choice I u32 is abstract
    o parser I := parser.this
    map(I2 type, m I -> I2) : parser I2 is
      parse(i2 i32) choice I2 u32 is
        match o.parse i2
          i3 I => i3
          u u32 => u
```
the require condition failure is rather unrelated...
```
sam@debian ~/n/fuzion (lib/modules/nom_parser_no_ref_2)130$ fz ~/playground/test.fz 

/home/sam/playground/test.fz:9:11: error 1: 'case' clause in 'match' statement does not match any type of the subject.
          i3 I => i3
----------^
Case matches type 'test.parser.I'.
Subject type is one of 'test.parser.map.I2' or 'u32'.

java.lang.Error: require-condition3 failed: dev.flang.ast.Tag:<init>:80
	at dev.flang.util.ANY.require(ANY.java:113)
	at dev.flang.ast.Tag.<init>(Tag.java:80)
	at dev.flang.ast.Expr.tag(Expr.java:360)
	at dev.flang.ast.Expr.box(Expr.java:329)
	at dev.flang.ast.AbstractAssign.box(AbstractAssign.java:212)
	at dev.flang.ast.Feature$6.action(Feature.java:1688)
	at dev.flang.ast.AbstractAssign.visit(AbstractAssign.java:127)
	at dev.flang.ast.AbstractAssign.visit(AbstractAssign.java:40)
	at dev.flang.ast.Block.visit(Block.java:227)
	at dev.flang.ast.Case.visit(Case.java:202)
	at dev.flang.ast.Match.visit(Match.java:135)
	at dev.flang.ast.Match.visit(Match.java:48)
	at dev.flang.ast.Block.visit(Block.java:227)
	at dev.flang.ast.Block.visit(Block.java:41)
	at dev.flang.ast.Block.visit(Block.java:227)
	at dev.flang.ast.Block.visit(Block.java:41)
	at dev.flang.ast.Impl.visit(Impl.java:312)
	at dev.flang.ast.Feature.visit(Feature.java:1038)
	at dev.flang.ast.Feature.box(Feature.java:1687)
	at dev.flang.ast.Resolution.resolveOne(Resolution.java:390)
	at dev.flang.ast.Resolution.resolve(Resolution.java:338)
	at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:260)
	at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:176)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:830)
	at dev.flang.tools.Tool.run(Tool.java:153)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)

``

**Comment by fridis** [comment]
This causes an error now: 
```
> PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz ex_659.fz 

/home/fridi/fuzion/work/ex_659.fz:7:15: error 1: Ambiguous targets found for call to 'o'
        match o.parse i2
--------------^
Found several possible call targets within the current feature at different levels of outer features:
in 'test.parser.map' found 'test.parser.o' defined at /home/fridi/fuzion/work/ex_659.fz:4:5:
    o parser I := parser.this
----^
and in 'test.parser' found 'test.parser.o' defined at /home/fridi/fuzion/work/ex_659.fz:4:5:
    o parser I := parser.this
----^
To solve this, you may qualify the feature using 'test.parser.map.this.o' or 'test.parser.this.o'.

one error.
```
chosing the first suggested alternative
```
test =>
  parser(I type) ref is
    parse(i i32) choice I u32 is abstract
    o parser I := parser.this
    map(I2 type, m I -> I2) : parser I2 is
      parse(i2 i32) choice I2 u32 is
        match test.parser.this.o.parse i2
          i3 I => i3
          u u32 => u
```
we get another error
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz ex_659a.fz 

/home/fridi/fuzion/work/ex_659a.fz:8:11: error 1: 'case' clause in 'match' statement does not match any type of the subject.
          i3 I => i3
----------^
Case matches type 'test.parser.I'.
Subject type is one of 'test.parser.map.I2' or 'u32'.

one error.
```
Looks as if type parameter replacement goes too far and has replaced `I` by `I2`.
