### ISSUE TITLE
NullPointerException when using anonymous features

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#698]
```
ex_tree is
  Node(A, B, C type) ref is
    datum A is abstract
    count i32 is abstract
    left B is abstract
    right C is abstract

  tree(A (ordered A).type) : choice nil (Node A (tree A) (tree A)) is
    
    size i32 is
      tree.this ? nil    => 0
                | n Node => n.count

    private smart (datum A, left, right tree A) tree A is
      ref : Node A (tree A) (tree A)
        datum A is datum
        count i32 is (1 + left.size + right.size)
        left tree A is left
        right tree A is right

  trees is
    empty(A (ordered A).type) tree A is
      nil

  x := (trees.empty i32).smart 42 nil nil
  say x
```
crashes
```

error 1: *** java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
Call stack:
ex_tree.tree<i32>.smart.ref #anonymous0: ex_tree.fz:15:13:
      ref : Node A (tree A) (tree A)
------------^
ex_tree.tree<i32>.smart: ex_tree.fz:15:7:
      ref : Node A (tree A) (tree A)
------^
ex_tree: ex_tree.fz:25:26:
  x := (trees.empty i32).smart 42 nil nil
-------------------------^



error 2: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at dev.flang.be.interpreter.Layout.offset(Layout.java:253)
	at dev.flang.be.interpreter.Interpreter$1.call(Interpreter.java:769)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:319)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:483)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:639)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:879)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:799)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:319)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:569)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:366)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:330)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:366)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:917)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:799)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:319)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:330)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:366)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:366)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:917)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:799)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:227)
	at dev.flang.tools.Fuzion$Backend$1.process(Fuzion.java:103)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:368)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:832)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:686)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)
```
(attempting to compile with the C backend returns a different error)

**Comment by michaellilltokiwa** [comment]
The bugs in the backends could be unrelated.
This still crashes in interpreter but c backend works:
```
ex_tree is
  Node ref is

  tree : choice nil Node is
    smart tree is
      ref : Node

  trees is
    empty tree is
      nil

  say trees.empty.smart
```

**Comment by michaellilltokiwa** [comment]
I think I know the reason now. `ref : Node` seems to need a closure here which is not allowed for choice types.
With this patch:
```patch
diff --git a/src/dev/flang/ast/Feature.java b/src/dev/flang/ast/Feature.java
index 1db72d54..4f25b1fe 100644
--- a/src/dev/flang/ast/Feature.java
+++ b/src/dev/flang/ast/Feature.java
@@ -1429,7 +1429,7 @@ public class Feature extends AbstractFeature implements Stmnt
     for (AbstractFeature af : res._module.declaredOrInheritedFeatures(this).values())
       {
         af.visitStatements(s -> {
-            if (s instanceof AbstractCall c && c.calledFeature() == outerRef())
+            if (s instanceof AbstractCall c && (c.calledFeature() == outerRef() || c.calledFeature().inherits().stream().anyMatch(ihc -> ihc.target().isCallToOuterRef())))
               {
                 result.add(c);
               }
```
The error for the above example is:
```
/home/sam/playground/test.fz:8:3: error 1: Choice type must not access fields of surrounding scope.
  tree(A (ordered A).type) : choice nil (Node A (tree A) (tree A)) is
--^
A closure cannot be built for a choice type. Forbidden accesses occur at 
/home/sam/playground/test.fz:15:7:
      ref : Node A (tree A) (tree A)
------^

one error.
```
If we move Node outside of ex_tree it works in interpreter and c backend:
```
ex_tree is
  tree(A (ordered A).type) : choice nil (Node A (tree A) (tree A)) is

    size i32 is
      tree.this ? nil    => 0
                | n Node => n.count

    private smart (datum A, left, right tree A) tree A is
      ref : Node A (tree A) (tree A)
        datum A is datum
        count i32 is (1 + left.size + right.size)
        left tree A is left
        right tree A is right

  trees is
    empty(A (ordered A).type) tree A is
      nil

  x := (trees.empty i32).smart 42 nil nil
  say x

Node(A, B, C type) ref is
  datum A is abstract
  count i32 is abstract
  left B is abstract
  right C is abstract

_ := ex_tree
```
