### ISSUE TITLE
modules test fails when re-running tests

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#798]
When re-running tests, i.e. running `make run_tests_parallel` for a second time, the test fails:

```
error 1: java.lang.ArrayIndexOutOfBoundsException: Index 14 out of bounds for length 7
	at dev.flang.ast.AbstractFeature$Kind.from(AbstractFeature.java:81)
	at dev.flang.fe.LibraryModule.featureKindEnum(LibraryModule.java:897)
	at dev.flang.fe.LibraryFeature.<init>(LibraryFeature.java:179)
	at dev.flang.fe.LibraryModule.libraryFeature(LibraryModule.java:312)
	at dev.flang.fe.LibraryModule.libraryFeature(LibraryModule.java:323)
	at dev.flang.fe.LibraryModule.feature(LibraryModule.java:340)
	at dev.flang.fe.LibraryModule.features(LibraryModule.java:358)
	at dev.flang.fe.LibraryModule.declaredFeatures(LibraryModule.java:289)
	at dev.flang.fe.SourceModule.declaredFeatures(SourceModule.java:689)
	at dev.flang.fe.SourceModule.addDeclaredInnerFeature(SourceModule.java:830)
	at dev.flang.fe.SourceModule.setOuterAndAddInner(SourceModule.java:558)
	at dev.flang.fe.SourceModule.findDeclarations(SourceModule.java:450)
	at dev.flang.ast.Feature.<init>(Feature.java:434)
	at dev.flang.ast.Feature.addOuterRef(Feature.java:2391)
	at dev.flang.fe.SourceModule.setOuterAndAddInner(SourceModule.java:554)
	at dev.flang.fe.SourceModule.findDeclarations(SourceModule.java:450)
	at dev.flang.fe.SourceModule.lambda$loadInnerFeatures$2(SourceModule.java:394)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at dev.flang.fe.SourceModule.loadInnerFeatures(SourceModule.java:390)
	at dev.flang.fe.SourceModule.declaredFeatures(SourceModule.java:703)
	at dev.flang.fe.Module.declaredOrInheritedFeatures(Module.java:325)
	at dev.flang.fe.SourceModule.lookupFeatures(SourceModule.java:968)
	at dev.flang.fe.SourceModule.lookupFeatureForType(SourceModule.java:1102)
	at dev.flang.fe.SourceModule.lambda$createASTandResolve$0(SourceModule.java:249)
	at dev.flang.ast.Types$Resolved.<init>(Types.java:178)
	at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:246)
	at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:188)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:830)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:686)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)
```

This same error is also shown for the C tests, so the problem does not happen at runtime but in the fuzion tool.

Removing the `build/tests` directory before running the tests stops this from happening.

**Comment by michaellilltokiwa** [comment]
meanwhile fixed, i think.
