### ISSUE TITLE
support swapping  values, (a,b) := (b,a)

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#830]
```
> cat ex21.fz
ex21 is

  a := 33
  b := 77
  say "a is $a b is $b"
  (a,b) := (b,a)
  say "a¹ is $a¹ b¹ is $b¹"
 > ./build/bin/fz ex21.fz

error 1: java.lang.NullPointerException: Cannot invoke "dev.flang.ast.AbstractFeature.isUniverse()" because the return value of "dev.flang.ast.AbstractFeature.outer()" is null
	at dev.flang.ast.AbstractFeature.existingOrNewTypeFeature(AbstractFeature.java:580)
	at dev.flang.ast.AbstractFeature.typeFeature(AbstractFeature.java:559)
	at dev.flang.ast.Call.resolveType(Call.java:1302)
	at dev.flang.ast.Call.resolveTypes(Call.java:1786)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1302)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1294)
	at dev.flang.ast.Call.visit(Call.java:1043)
	at dev.flang.ast.Destructure.visit(Destructure.java:220)
	at dev.flang.ast.Block.visit(Block.java:227)
	at dev.flang.ast.Block.visit(Block.java:41)
	at dev.flang.ast.Block.visit(Block.java:227)
	at dev.flang.ast.Block.visit(Block.java:41)
	at dev.flang.ast.Impl.visit(Impl.java:319)
	at dev.flang.ast.Feature.visit(Feature.java:1058)
	at dev.flang.ast.Feature.internalResolveTypes(Feature.java:1339)
	at dev.flang.ast.Resolution.resolveOne(Resolution.java:371)
	at dev.flang.ast.Resolution.resolve(Resolution.java:338)
	at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:264)
	at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:188)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:830)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:686)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)


*** fatal errors encountered, stopping.

```

**Comment by michaellilltokiwa** [comment]
Now an error: 
```
/home/sam/playground/test.fz:5:12: error 1: Incompatible type parameter
  (a,b) := (b,a)
-----------^
formal type parameter 'A' with constraint 'Any'
actual type parameter '--UNDEFINED--'
```

**Comment by michaellilltokiwa** [comment]
since we disallow variable shadowing now, this does not make sense anymore.
