### ISSUE TITLE
Problems with `.this` used in loop

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#874]
This fails with NYI
```
 > cat test_this.fz
test_this is

  n is
    m => 3
    l =>
      for
        x := n.this
        y := x.m
      do

  i : n.

  i.l
#  n.l
 > ./build/bin/fz -c test_this.fz 

error 1: NYI: in test_this.i.l no targets for Call to test_this.n.m target UNIT

one error.
```
And this fails with an empty stack:
```
 > cat test_this2.fz
test_this is

  n is
    m => 3
    l =>
      for
        x := n.this
        y := x.m
      do

  i : n.

#  i.l
  n.l
 > ./build/bin/fz -c test_this2.fz 

error 1: java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:101)
	at java.base/java.util.Stack.pop(Stack.java:83)
	at dev.flang.fuir.analysis.Escape.doesCurEscape(Escape.java:194)
	at dev.flang.fuir.analysis.Escape.doesCurEscapeCached(Escape.java:123)
	at dev.flang.fuir.analysis.Escape.doesCurEscape(Escape.java:104)
	at dev.flang.be.c.C.current(C.java:1310)
	at dev.flang.be.c.C$CodeGen.current(C.java:212)
	at dev.flang.fuir.analysis.AbstractInterpreter.assignOuterAndArgFields(AbstractInterpreter.java:366)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:405)
	at dev.flang.be.c.C.codeForRoutine(C.java:1283)
	at dev.flang.be.c.C.code(C.java:1251)
	at dev.flang.be.c.C$CompilePhase$4.compile(C.java:417)
	at dev.flang.be.c.C.lambda$createCode$4(C.java:640)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
	at dev.flang.be.c.C.createCode(C.java:636)
	at dev.flang.be.c.C.compile(C.java:524)
	at dev.flang.tools.Fuzion$Backend$2.process(Fuzion.java:145)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:368)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:832)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:686)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)


*** fatal errors encountered, stopping.

```

**Comment by fridis** [comment]
Two more test cases that still fail:
```
> cat test_this3.fz
test_this3 is

  num is

    type.zero num.this.type is abstract
    type.one  num.this.type is abstract
    lessThan(other num.this.type) bool is abstract
    minus(other num.this.type) num.this.type is abstract

    to_u32_loop =>
      for
        x := num.this, x.minus num.this.type.one
        u := u32 0, u+1
      while num.this.type.zero.lessThan x

    redef asString => "num.this.type {to_u32_loop} 'asString'"

  intM5(v u8) : num is
    fixed type.zero => test_this3.intM5 0
    fixed type.one => test_this3.intM5 1
    fixed lessThan(other intM5) => v < other.v
    fixed plus(other intM5) => intM5 (v + other.v)%5

y := test_this3.intM5 1
say (y.plus y)
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c test_this3.fz  

error 1: java.lang.Error: require-condition1 failed: dev.flang.air.Clazz:lookup:996
	at dev.flang.util.ANY.require(ANY.java:93)
	at dev.flang.air.Clazz.lookup(Clazz.java:996)
	at dev.flang.air.Clazz.findOuter(Clazz.java:2049)
	at dev.flang.air.Clazz.determineResultClazz(Clazz.java:2095)
	at dev.flang.air.Clazz.dependencies(Clazz.java:410)
	at dev.flang.air.Clazzes.create(Clazzes.java:388)
	at dev.flang.air.Clazzes.clazzWithSpecificOuter(Clazzes.java:1219)
	at dev.flang.air.Clazz.lookup(Clazz.java:1128)
	at dev.flang.air.Clazz.lookup(Clazz.java:1030)
	at dev.flang.air.Clazz.lookup(Clazz.java:999)
	at dev.flang.air.Clazz.lookup(Clazz.java:972)
	at dev.flang.air.Clazz.lookupIfInstantiated(Clazz.java:923)
	at dev.flang.air.Clazz.lambda$findAllClasses$1(Clazz.java:1399)
	at dev.flang.air.Clazzes.calledDynamically(Clazzes.java:557)
	at dev.flang.air.Clazzes.findClazzes(Clazzes.java:866)
	at dev.flang.air.Clazz$1.action(Clazz.java:1383)
	at dev.flang.ast.Stmnt.visitStatements(Stmnt.java:72)
	at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:123)
	at dev.flang.ast.AbstractAssign.visitStatements(AbstractAssign.java:140)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.If.visitStatements(If.java:288)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractAssign.visitStatements(AbstractAssign.java:140)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractFeature.visitStatements(AbstractFeature.java:1330)
	at dev.flang.air.Clazz.inspectCode(Clazz.java:1333)
	at dev.flang.air.Clazz.findAllClasses(Clazz.java:1377)
	at dev.flang.air.Clazzes.findAllClasses(Clazzes.java:455)
	at dev.flang.fuir.FUIR.<init>(FUIR.java:196)
	at dev.flang.opt.Optimizer.fuir(Optimizer.java:73)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:367)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:832)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:686)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)


*** fatal errors encountered, stopping.
```
and
```
 > cat test_this4.fz
test_this4 is

  num is

    type.zero num.this.type is abstract
    type.one  num.this.type is abstract
    lessThan(other num.this.type) bool is abstract
    minus(other num.this.type) num.this.type is abstract

    to_u32_loop =>
      for
        x := num.this, x.minus num.this.type.one
        u := u32 0, u+1
      while num.this.type.zero.lessThan x
      else
        u

    redef asString => "num.this.type {to_u32_loop} 'asString'"


  intM5(v u8) : num is
    fixed type.zero => test_this4.intM5 0
    fixed type.one => test_this4.intM5 1
    fixed lessThan(other intM5) => v < other.v
    fixed plus(other intM5) => intM5 (v + other.v)%5
    fixed minus(other intM5) => intM5 (v - other.v)%5

y := test_this4.intM5 1
say (y.plus y)
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c test_this4.fz  

error 1: NYI: in test_this4.ref intM5.to_u32_loop.#loop0 no targets for Call to test_this4.ref intM5.minus target test_this4.intM5

one error.
```

**Comment by fridis** [comment]
Closing this since the original related issues have been fixed. 

There is still #905, which is similar and open.
