### ISSUE TITLE
DFA: small example causes pop on empty stack

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#890]
This occurred while tracking down issues for #874: 

```
 > cat test_cov_DFA_pop.fz 
test_cov is

  n is

    plus (other n.this.type) n.this.type is abstract

    to_u32_loop =>
      x := n.this
      y := x.plus n.this

    redef asString => "{to_u32_loop}"

  i : n is
    fixed plus(other i) => other

say (test_cov.i)
 > fz -c test_cov_DFA_pop.fz 

error 1: java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:101)
	at java.base/java.util.Stack.pop(Stack.java:83)
	at dev.flang.fuir.analysis.AbstractInterpreter.pop(AbstractInterpreter.java:311)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:525)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:442)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:408)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:880)
	at dev.flang.fuir.analysis.dfa.DFA.iteration(DFA.java:845)
	at dev.flang.fuir.analysis.dfa.DFA.findFixPoint(DFA.java:808)
	at dev.flang.fuir.analysis.dfa.DFA.dfa(DFA.java:790)
	at dev.flang.fuir.analysis.dfa.DFA.new_fuir(DFA.java:719)
	at dev.flang.be.c.C.<init>(C.java:495)
	at dev.flang.tools.Fuzion$Backend$2.process(Fuzion.java:145)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:368)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:832)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:686)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)


*** fatal errors encountered, stopping.

```

**Comment by fridis** [comment]
Here is a smaller (maybe even minimal) example: 

```
> cat test_cov_DFA_pop.fz
n is
  r =>
    x := n.this
    x.asString

i : n is

o ref n := i
_ := o.r
 > PRECONDITIONS=true POSTCONDITIONS=true build/bin/fz -c test_cov_DFA_pop.fz

error 1: java.lang.Error: require-condition1 failed: dev.flang.fuir.analysis.AbstractInterpreter:pop:307
[...]
*** fatal errors encountered, stopping.
```
The problem seems to be that the type of 'i.r.x' is 'ref i' while the value on the stack is a unit type value (which means it is not stored on the stack).
